/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type {
  BrEggControllerFindAllParams,
  BrPetControllerFindAllParams,
  CreateEggDto,
  CreateInitUserInfoDto,
  CreateParentDto,
  CreatePetDto,
  CreateUserNotificationDto,
  DeleteUserNotificationDto,
  ParentControllerFindParentParams,
  PetControllerFindAllParams,
  PetControllerGetPetsWithChildrenParams,
  UpdateEggDto,
  UpdateParentDto,
  UpdatePetDto,
  UpdateUserNotificationDto,
  UserNotificationControllerFindAllParams,
} from "../model";

import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";

import type {
  BrEggControllerFindAll200,
  BrPetControllerFindAll200,
  CommonResponseDto,
  EggDto,
  HatchedResponseDto,
  ParentDto,
  PetControllerFindAll200,
  PetControllerGetPetsWithChildren200,
  PetDto,
  TokenResponseDto,
  UserNotificationControllerFindAll200,
  UserProfileDto,
} from "../model";

import { useCustomInstance } from "./mutator/use-custom-instance";
export const petControllerFindAll = (params?: PetControllerFindAllParams) => {
  return useCustomInstance<PetControllerFindAll200>({
    url: `http://localhost:4000/api/v1/pet`,
    method: "GET",
    params,
  });
};

export const petControllerCreate = (createPetDto: CreatePetDto) => {
  return useCustomInstance<CommonResponseDto>({
    url: `http://localhost:4000/api/v1/pet`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createPetDto,
  });
};

export const petControllerGetPetsWithChildren = (
  params?: PetControllerGetPetsWithChildrenParams,
) => {
  return useCustomInstance<PetControllerGetPetsWithChildren200>({
    url: `http://localhost:4000/api/v1/pet/children`,
    method: "GET",
    params,
  });
};

export const petControllerFindOne = (petId: string) => {
  return useCustomInstance<PetDto>({
    url: `http://localhost:4000/api/v1/pet/${petId}`,
    method: "GET",
  });
};

export const petControllerUpdate = (petId: string, updatePetDto: UpdatePetDto) => {
  return useCustomInstance<CommonResponseDto>({
    url: `http://localhost:4000/api/v1/pet/${petId}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: updatePetDto,
  });
};

export const petControllerDelete = (petId: string) => {
  return useCustomInstance<void>({
    url: `http://localhost:4000/api/v1/pet/${petId}`,
    method: "DELETE",
  });
};

export const parentControllerFindParent = (
  petId: string,
  params: ParentControllerFindParentParams,
) => {
  return useCustomInstance<ParentDto>({
    url: `http://localhost:4000/api/v1/parent/${petId}`,
    method: "GET",
    params,
  });
};

export const parentControllerCreateParent = (petId: string, createParentDto: CreateParentDto) => {
  return useCustomInstance<CommonResponseDto>({
    url: `http://localhost:4000/api/v1/parent/${petId}`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createParentDto,
  });
};

export const parentControllerUpdateParentRequest = (updateParentDto: UpdateParentDto) => {
  return useCustomInstance<CommonResponseDto>({
    url: `http://localhost:4000/api/v1/parent/update`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: updateParentDto,
  });
};

export const parentControllerDeleteParent = (relationId: number) => {
  return useCustomInstance<CommonResponseDto>({
    url: `http://localhost:4000/api/v1/parent/delete/${relationId}`,
    method: "DELETE",
  });
};

export const userNotificationControllerFindAll = (
  params?: UserNotificationControllerFindAllParams,
) => {
  return useCustomInstance<UserNotificationControllerFindAll200>({
    url: `http://localhost:4000/api/v1/user-notification`,
    method: "GET",
    params,
  });
};

export const userNotificationControllerCreate = (
  createUserNotificationDto: CreateUserNotificationDto,
) => {
  return useCustomInstance<CommonResponseDto>({
    url: `http://localhost:4000/api/v1/user-notification`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createUserNotificationDto,
  });
};

export const userNotificationControllerUpdate = (
  updateUserNotificationDto: UpdateUserNotificationDto,
) => {
  return useCustomInstance<CommonResponseDto>({
    url: `http://localhost:4000/api/v1/user-notification`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: updateUserNotificationDto,
  });
};

export const userNotificationControllerDelete = (
  deleteUserNotificationDto: DeleteUserNotificationDto,
) => {
  return useCustomInstance<CommonResponseDto>({
    url: `http://localhost:4000/api/v1/user-notification`,
    method: "DELETE",
    headers: { "Content-Type": "application/json" },
    data: deleteUserNotificationDto,
  });
};

export const brPetControllerFindAll = (params?: BrPetControllerFindAllParams) => {
  return useCustomInstance<BrPetControllerFindAll200>({
    url: `http://localhost:4000/api/v1/br/pet`,
    method: "GET",
    params,
  });
};

export const eggControllerFindOne = (eggId: string) => {
  return useCustomInstance<EggDto>({
    url: `http://localhost:4000/api/v1/egg/${eggId}`,
    method: "GET",
  });
};

export const eggControllerUpdate = (eggId: string, updateEggDto: UpdateEggDto) => {
  return useCustomInstance<CommonResponseDto>({
    url: `http://localhost:4000/api/v1/egg/${eggId}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: updateEggDto,
  });
};

export const eggControllerDelete = (eggId: string) => {
  return useCustomInstance<CommonResponseDto>({
    url: `http://localhost:4000/api/v1/egg/${eggId}`,
    method: "DELETE",
  });
};

export const eggControllerCreate = (createEggDto: CreateEggDto) => {
  return useCustomInstance<CommonResponseDto>({
    url: `http://localhost:4000/api/v1/egg`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createEggDto,
  });
};

export const eggControllerHatched = (eggId: string) => {
  return useCustomInstance<HatchedResponseDto>({
    url: `http://localhost:4000/api/v1/egg/${eggId}/hatched`,
    method: "GET",
  });
};

export const brEggControllerFindAll = (params?: BrEggControllerFindAllParams) => {
  return useCustomInstance<BrEggControllerFindAll200>({
    url: `http://localhost:4000/api/v1/br/egg`,
    method: "GET",
    params,
  });
};

export const authControllerKakaoLogin = () => {
  return useCustomInstance<unknown>({
    url: `http://localhost:4000/api/auth/sign-in/kakao`,
    method: "GET",
  });
};

export const authControllerGoogleLogin = () => {
  return useCustomInstance<unknown>({
    url: `http://localhost:4000/api/auth/sign-in/google`,
    method: "GET",
  });
};

export const authControllerGetToken = () => {
  return useCustomInstance<TokenResponseDto>({
    url: `http://localhost:4000/api/auth/token`,
    method: "GET",
  });
};

export const authControllerSignOut = () => {
  return useCustomInstance<void>({
    url: `http://localhost:4000/api/auth/sign-out`,
    method: "POST",
  });
};

export const authControllerDeleteAccount = () => {
  return useCustomInstance<void>({
    url: `http://localhost:4000/api/auth/delete-account`,
    method: "POST",
  });
};

export const userControllerGetUserProfile = () => {
  return useCustomInstance<UserProfileDto>({
    url: `http://localhost:4000/api/v1/user/profile`,
    method: "GET",
  });
};

export const userControllerCreateInitUserInfo = (createInitUserInfoDto: CreateInitUserInfoDto) => {
  return useCustomInstance<CommonResponseDto>({
    url: `http://localhost:4000/api/v1/user/init-info`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createInitUserInfoDto,
  });
};

export type PetControllerFindAllResult = NonNullable<
  Awaited<ReturnType<typeof petControllerFindAll>>
>;
export type PetControllerCreateResult = NonNullable<
  Awaited<ReturnType<typeof petControllerCreate>>
>;
export type PetControllerGetPetsWithChildrenResult = NonNullable<
  Awaited<ReturnType<typeof petControllerGetPetsWithChildren>>
>;
export type PetControllerFindOneResult = NonNullable<
  Awaited<ReturnType<typeof petControllerFindOne>>
>;
export type PetControllerUpdateResult = NonNullable<
  Awaited<ReturnType<typeof petControllerUpdate>>
>;
export type PetControllerDeleteResult = NonNullable<
  Awaited<ReturnType<typeof petControllerDelete>>
>;
export type ParentControllerFindParentResult = NonNullable<
  Awaited<ReturnType<typeof parentControllerFindParent>>
>;
export type ParentControllerCreateParentResult = NonNullable<
  Awaited<ReturnType<typeof parentControllerCreateParent>>
>;
export type ParentControllerUpdateParentRequestResult = NonNullable<
  Awaited<ReturnType<typeof parentControllerUpdateParentRequest>>
>;
export type ParentControllerDeleteParentResult = NonNullable<
  Awaited<ReturnType<typeof parentControllerDeleteParent>>
>;
export type UserNotificationControllerFindAllResult = NonNullable<
  Awaited<ReturnType<typeof userNotificationControllerFindAll>>
>;
export type UserNotificationControllerCreateResult = NonNullable<
  Awaited<ReturnType<typeof userNotificationControllerCreate>>
>;
export type UserNotificationControllerUpdateResult = NonNullable<
  Awaited<ReturnType<typeof userNotificationControllerUpdate>>
>;
export type UserNotificationControllerDeleteResult = NonNullable<
  Awaited<ReturnType<typeof userNotificationControllerDelete>>
>;
export type BrPetControllerFindAllResult = NonNullable<
  Awaited<ReturnType<typeof brPetControllerFindAll>>
>;
export type EggControllerFindOneResult = NonNullable<
  Awaited<ReturnType<typeof eggControllerFindOne>>
>;
export type EggControllerUpdateResult = NonNullable<
  Awaited<ReturnType<typeof eggControllerUpdate>>
>;
export type EggControllerDeleteResult = NonNullable<
  Awaited<ReturnType<typeof eggControllerDelete>>
>;
export type EggControllerCreateResult = NonNullable<
  Awaited<ReturnType<typeof eggControllerCreate>>
>;
export type EggControllerHatchedResult = NonNullable<
  Awaited<ReturnType<typeof eggControllerHatched>>
>;
export type BrEggControllerFindAllResult = NonNullable<
  Awaited<ReturnType<typeof brEggControllerFindAll>>
>;
export type AuthControllerKakaoLoginResult = NonNullable<
  Awaited<ReturnType<typeof authControllerKakaoLogin>>
>;
export type AuthControllerGoogleLoginResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGoogleLogin>>
>;
export type AuthControllerGetTokenResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetToken>>
>;
export type AuthControllerSignOutResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignOut>>
>;
export type AuthControllerDeleteAccountResult = NonNullable<
  Awaited<ReturnType<typeof authControllerDeleteAccount>>
>;
export type UserControllerGetUserProfileResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetUserProfile>>
>;
export type UserControllerCreateInitUserInfoResult = NonNullable<
  Awaited<ReturnType<typeof userControllerCreateInitUserInfo>>
>;

export const getPetControllerFindAllResponseMock = (
  overrideResponse: Partial<PetControllerFindAll200> = {},
): PetControllerFindAll200 => ({
  data: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    petId: faker.string.alpha(20),
    owner: {
      ...{
        userId: faker.string.alpha(20),
        name: faker.string.alpha(20),
        role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
        isBiz: faker.datatype.boolean(),
        status: faker.helpers.arrayElement([
          "pending",
          "active",
          "inactive",
          "suspended",
          "deleted",
        ] as const),
      },
    },
    name: faker.string.alpha(20),
    species: faker.helpers.arrayElement(["CR", "LE", "FT", "KN", "LC", "GG"] as const),
    morphs: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
        faker.string.alpha(20),
      ),
      undefined,
    ]),
    traits: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
        faker.string.alpha(20),
      ),
      undefined,
    ]),
    sex: faker.helpers.arrayElement([
      faker.helpers.arrayElement(["M", "F", "N"] as const),
      undefined,
    ]),
  })),
  meta: {
    page: faker.number.int({ min: undefined, max: undefined }),
    itemPerPage: faker.number.int({ min: undefined, max: undefined }),
    totalCount: faker.number.int({ min: undefined, max: undefined }),
    totalPage: faker.number.int({ min: undefined, max: undefined }),
    hasPreviousPage: faker.datatype.boolean(),
    hasNextPage: faker.datatype.boolean(),
  },
  ...overrideResponse,
});

export const getPetControllerCreateResponseMock = (
  overrideResponse: Partial<CommonResponseDto> = {},
): CommonResponseDto => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha(20),
  ...overrideResponse,
});

export const getPetControllerGetPetsWithChildrenResponseMock = (
  overrideResponse: Partial<PetControllerGetPetsWithChildren200> = {},
): PetControllerGetPetsWithChildren200 => ({
  data: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    parent: {
      ...{
        petId: faker.string.alpha(20),
        owner: {
          ...{
            userId: faker.string.alpha(20),
            name: faker.string.alpha(20),
            role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
            isBiz: faker.datatype.boolean(),
            status: faker.helpers.arrayElement([
              "pending",
              "active",
              "inactive",
              "suspended",
              "deleted",
            ] as const),
          },
        },
        name: faker.string.alpha(20),
        species: faker.helpers.arrayElement(["CR", "LE", "FT", "KN", "LC", "GG"] as const),
        morphs: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        traits: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        sex: faker.helpers.arrayElement([
          faker.helpers.arrayElement(["M", "F", "N"] as const),
          undefined,
        ]),
      },
    },
    children: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
      () => ({
        petId: faker.string.alpha(20),
        owner: {
          ...{
            userId: faker.string.alpha(20),
            name: faker.string.alpha(20),
            role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
            isBiz: faker.datatype.boolean(),
            status: faker.helpers.arrayElement([
              "pending",
              "active",
              "inactive",
              "suspended",
              "deleted",
            ] as const),
          },
        },
        name: faker.string.alpha(20),
        species: faker.helpers.arrayElement(["CR", "LE", "FT", "KN", "LC", "GG"] as const),
        morphs: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        traits: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        sex: faker.helpers.arrayElement([
          faker.helpers.arrayElement(["M", "F", "N"] as const),
          undefined,
        ]),
      }),
    ),
    childrenCount: faker.number.int({ min: undefined, max: undefined }),
  })),
  meta: {
    page: faker.number.int({ min: undefined, max: undefined }),
    itemPerPage: faker.number.int({ min: undefined, max: undefined }),
    totalCount: faker.number.int({ min: undefined, max: undefined }),
    totalPage: faker.number.int({ min: undefined, max: undefined }),
    hasPreviousPage: faker.datatype.boolean(),
    hasNextPage: faker.datatype.boolean(),
  },
  ...overrideResponse,
});

export const getPetControllerFindOneResponseMock = (
  overrideResponse: Partial<PetDto> = {},
): PetDto => ({
  petId: faker.string.alpha(20),
  owner: {
    ...{
      userId: faker.string.alpha(20),
      name: faker.string.alpha(20),
      role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
      isBiz: faker.datatype.boolean(),
      status: faker.helpers.arrayElement([
        "pending",
        "active",
        "inactive",
        "suspended",
        "deleted",
      ] as const),
    },
  },
  name: faker.string.alpha(20),
  species: faker.helpers.arrayElement(["CR", "LE", "FT", "KN", "LC", "GG"] as const),
  morphs: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
      faker.string.alpha(20),
    ),
    undefined,
  ]),
  traits: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
      faker.string.alpha(20),
    ),
    undefined,
  ]),
  birthdate: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  growth: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  saleStatus: faker.helpers.arrayElement([
    faker.helpers.arrayElement(["NFS", "ON_SALE", "ON_RESERVATION", "SOLD"] as const),
    undefined,
  ]),
  isPublic: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  sex: faker.helpers.arrayElement([
    faker.helpers.arrayElement(["M", "F", "N"] as const),
    undefined,
  ]),
  weight: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  foods: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
      faker.string.alpha(20),
    ),
    undefined,
  ]),
  desc: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  father: faker.helpers.arrayElement([
    {
      ...{
        petId: faker.string.alpha(20),
        owner: {
          ...{
            userId: faker.string.alpha(20),
            name: faker.string.alpha(20),
            role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
            isBiz: faker.datatype.boolean(),
            status: faker.helpers.arrayElement([
              "pending",
              "active",
              "inactive",
              "suspended",
              "deleted",
            ] as const),
          },
        },
        name: faker.string.alpha(20),
        species: faker.helpers.arrayElement(["CR", "LE", "FT", "KN", "LC", "GG"] as const),
        morphs: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        traits: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        sex: faker.helpers.arrayElement([
          faker.helpers.arrayElement(["M", "F", "N"] as const),
          undefined,
        ]),
        relationId: faker.number.int({ min: undefined, max: undefined }),
        status: faker.helpers.arrayElement([
          "pending",
          "approved",
          "rejected",
          "deleted",
          "cancelled",
        ] as const),
      },
    },
    undefined,
  ]),
  mother: faker.helpers.arrayElement([
    {
      ...{
        petId: faker.string.alpha(20),
        owner: {
          ...{
            userId: faker.string.alpha(20),
            name: faker.string.alpha(20),
            role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
            isBiz: faker.datatype.boolean(),
            status: faker.helpers.arrayElement([
              "pending",
              "active",
              "inactive",
              "suspended",
              "deleted",
            ] as const),
          },
        },
        name: faker.string.alpha(20),
        species: faker.helpers.arrayElement(["CR", "LE", "FT", "KN", "LC", "GG"] as const),
        morphs: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        traits: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        sex: faker.helpers.arrayElement([
          faker.helpers.arrayElement(["M", "F", "N"] as const),
          undefined,
        ]),
        relationId: faker.number.int({ min: undefined, max: undefined }),
        status: faker.helpers.arrayElement([
          "pending",
          "approved",
          "rejected",
          "deleted",
          "cancelled",
        ] as const),
      },
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getPetControllerUpdateResponseMock = (
  overrideResponse: Partial<CommonResponseDto> = {},
): CommonResponseDto => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha(20),
  ...overrideResponse,
});

export const getParentControllerFindParentResponseMock = (
  overrideResponse: Partial<ParentDto> = {},
): ParentDto => ({
  relationId: faker.number.int({ min: undefined, max: undefined }),
  parentId: faker.string.alpha(20),
  role: faker.helpers.arrayElement(["father", "mother"] as const),
  status: faker.helpers.arrayElement([
    "pending",
    "approved",
    "rejected",
    "deleted",
    "cancelled",
  ] as const),
  ...overrideResponse,
});

export const getParentControllerCreateParentResponseMock = (
  overrideResponse: Partial<CommonResponseDto> = {},
): CommonResponseDto => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha(20),
  ...overrideResponse,
});

export const getParentControllerUpdateParentRequestResponseMock = (
  overrideResponse: Partial<CommonResponseDto> = {},
): CommonResponseDto => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha(20),
  ...overrideResponse,
});

export const getParentControllerDeleteParentResponseMock = (
  overrideResponse: Partial<CommonResponseDto> = {},
): CommonResponseDto => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha(20),
  ...overrideResponse,
});

export const getUserNotificationControllerFindAllResponseMock = (
  overrideResponse: Partial<UserNotificationControllerFindAll200> = {},
): UserNotificationControllerFindAll200 => ({
  data: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    senderId: faker.string.alpha(20),
    receiverId: faker.string.alpha(20),
    type: faker.helpers.arrayElement([
      "parent_request",
      "parent_accept",
      "parent_reject",
      "owner_transfer",
      "owner_accept",
      "owner_reject",
    ] as const),
    targetId: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
    status: faker.helpers.arrayElement(["read", "unread", "deleted"] as const),
    detailJson: faker.helpers.arrayElement([{}, undefined]),
    createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
  })),
  meta: {
    page: faker.number.int({ min: undefined, max: undefined }),
    itemPerPage: faker.number.int({ min: undefined, max: undefined }),
    totalCount: faker.number.int({ min: undefined, max: undefined }),
    totalPage: faker.number.int({ min: undefined, max: undefined }),
    hasPreviousPage: faker.datatype.boolean(),
    hasNextPage: faker.datatype.boolean(),
  },
  ...overrideResponse,
});

export const getUserNotificationControllerCreateResponseMock = (
  overrideResponse: Partial<CommonResponseDto> = {},
): CommonResponseDto => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha(20),
  ...overrideResponse,
});

export const getUserNotificationControllerUpdateResponseMock = (
  overrideResponse: Partial<CommonResponseDto> = {},
): CommonResponseDto => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha(20),
  ...overrideResponse,
});

export const getUserNotificationControllerDeleteResponseMock = (
  overrideResponse: Partial<CommonResponseDto> = {},
): CommonResponseDto => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha(20),
  ...overrideResponse,
});

export const getBrPetControllerFindAllResponseMock = (
  overrideResponse: Partial<BrPetControllerFindAll200> = {},
): BrPetControllerFindAll200 => ({
  data: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    petId: faker.string.alpha(20),
    owner: {
      ...{
        userId: faker.string.alpha(20),
        name: faker.string.alpha(20),
        role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
        isBiz: faker.datatype.boolean(),
        status: faker.helpers.arrayElement([
          "pending",
          "active",
          "inactive",
          "suspended",
          "deleted",
        ] as const),
      },
    },
    name: faker.string.alpha(20),
    species: faker.helpers.arrayElement(["CR", "LE", "FT", "KN", "LC", "GG"] as const),
    morphs: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
        faker.string.alpha(20),
      ),
      undefined,
    ]),
    traits: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
        faker.string.alpha(20),
      ),
      undefined,
    ]),
    birthdate: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    growth: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
    saleStatus: faker.helpers.arrayElement([
      faker.helpers.arrayElement(["NFS", "ON_SALE", "ON_RESERVATION", "SOLD"] as const),
      undefined,
    ]),
    isPublic: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    sex: faker.helpers.arrayElement([
      faker.helpers.arrayElement(["M", "F", "N"] as const),
      undefined,
    ]),
    weight: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    foods: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
        faker.string.alpha(20),
      ),
      undefined,
    ]),
    desc: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
    father: faker.helpers.arrayElement([
      {
        ...{
          petId: faker.string.alpha(20),
          owner: {
            ...{
              userId: faker.string.alpha(20),
              name: faker.string.alpha(20),
              role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
              isBiz: faker.datatype.boolean(),
              status: faker.helpers.arrayElement([
                "pending",
                "active",
                "inactive",
                "suspended",
                "deleted",
              ] as const),
            },
          },
          name: faker.string.alpha(20),
          species: faker.helpers.arrayElement(["CR", "LE", "FT", "KN", "LC", "GG"] as const),
          morphs: faker.helpers.arrayElement([
            Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
              faker.string.alpha(20),
            ),
            undefined,
          ]),
          traits: faker.helpers.arrayElement([
            Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
              faker.string.alpha(20),
            ),
            undefined,
          ]),
          sex: faker.helpers.arrayElement([
            faker.helpers.arrayElement(["M", "F", "N"] as const),
            undefined,
          ]),
          relationId: faker.number.int({ min: undefined, max: undefined }),
          status: faker.helpers.arrayElement([
            "pending",
            "approved",
            "rejected",
            "deleted",
            "cancelled",
          ] as const),
        },
      },
      undefined,
    ]),
    mother: faker.helpers.arrayElement([
      {
        ...{
          petId: faker.string.alpha(20),
          owner: {
            ...{
              userId: faker.string.alpha(20),
              name: faker.string.alpha(20),
              role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
              isBiz: faker.datatype.boolean(),
              status: faker.helpers.arrayElement([
                "pending",
                "active",
                "inactive",
                "suspended",
                "deleted",
              ] as const),
            },
          },
          name: faker.string.alpha(20),
          species: faker.helpers.arrayElement(["CR", "LE", "FT", "KN", "LC", "GG"] as const),
          morphs: faker.helpers.arrayElement([
            Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
              faker.string.alpha(20),
            ),
            undefined,
          ]),
          traits: faker.helpers.arrayElement([
            Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
              faker.string.alpha(20),
            ),
            undefined,
          ]),
          sex: faker.helpers.arrayElement([
            faker.helpers.arrayElement(["M", "F", "N"] as const),
            undefined,
          ]),
          relationId: faker.number.int({ min: undefined, max: undefined }),
          status: faker.helpers.arrayElement([
            "pending",
            "approved",
            "rejected",
            "deleted",
            "cancelled",
          ] as const),
        },
      },
      undefined,
    ]),
  })),
  meta: {
    page: faker.number.int({ min: undefined, max: undefined }),
    itemPerPage: faker.number.int({ min: undefined, max: undefined }),
    totalCount: faker.number.int({ min: undefined, max: undefined }),
    totalPage: faker.number.int({ min: undefined, max: undefined }),
    hasPreviousPage: faker.datatype.boolean(),
    hasNextPage: faker.datatype.boolean(),
  },
  ...overrideResponse,
});

export const getEggControllerFindOneResponseMock = (
  overrideResponse: Partial<EggDto> = {},
): EggDto => ({
  eggId: faker.string.alpha(20),
  owner: {
    ...{
      userId: faker.string.alpha(20),
      name: faker.string.alpha(20),
      role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
      isBiz: faker.datatype.boolean(),
      status: faker.helpers.arrayElement([
        "pending",
        "active",
        "inactive",
        "suspended",
        "deleted",
      ] as const),
    },
  },
  species: faker.helpers.arrayElement(["CR", "LE", "FT", "KN", "LC", "GG"] as const),
  layingDate: faker.number.int({ min: undefined, max: undefined }),
  clutch: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  clutchOrder: faker.number.int({ min: undefined, max: undefined }),
  name: faker.string.alpha(20),
  desc: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  hatchedPetId: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  father: faker.helpers.arrayElement([
    {
      ...{
        petId: faker.string.alpha(20),
        owner: {
          ...{
            userId: faker.string.alpha(20),
            name: faker.string.alpha(20),
            role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
            isBiz: faker.datatype.boolean(),
            status: faker.helpers.arrayElement([
              "pending",
              "active",
              "inactive",
              "suspended",
              "deleted",
            ] as const),
          },
        },
        name: faker.string.alpha(20),
        species: faker.helpers.arrayElement(["CR", "LE", "FT", "KN", "LC", "GG"] as const),
        morphs: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        traits: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        sex: faker.helpers.arrayElement([
          faker.helpers.arrayElement(["M", "F", "N"] as const),
          undefined,
        ]),
        relationId: faker.number.int({ min: undefined, max: undefined }),
        status: faker.helpers.arrayElement([
          "pending",
          "approved",
          "rejected",
          "deleted",
          "cancelled",
        ] as const),
      },
    },
    undefined,
  ]),
  mother: faker.helpers.arrayElement([
    {
      ...{
        petId: faker.string.alpha(20),
        owner: {
          ...{
            userId: faker.string.alpha(20),
            name: faker.string.alpha(20),
            role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
            isBiz: faker.datatype.boolean(),
            status: faker.helpers.arrayElement([
              "pending",
              "active",
              "inactive",
              "suspended",
              "deleted",
            ] as const),
          },
        },
        name: faker.string.alpha(20),
        species: faker.helpers.arrayElement(["CR", "LE", "FT", "KN", "LC", "GG"] as const),
        morphs: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        traits: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        sex: faker.helpers.arrayElement([
          faker.helpers.arrayElement(["M", "F", "N"] as const),
          undefined,
        ]),
        relationId: faker.number.int({ min: undefined, max: undefined }),
        status: faker.helpers.arrayElement([
          "pending",
          "approved",
          "rejected",
          "deleted",
          "cancelled",
        ] as const),
      },
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getEggControllerUpdateResponseMock = (
  overrideResponse: Partial<CommonResponseDto> = {},
): CommonResponseDto => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha(20),
  ...overrideResponse,
});

export const getEggControllerDeleteResponseMock = (
  overrideResponse: Partial<CommonResponseDto> = {},
): CommonResponseDto => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha(20),
  ...overrideResponse,
});

export const getEggControllerCreateResponseMock = (
  overrideResponse: Partial<CommonResponseDto> = {},
): CommonResponseDto => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha(20),
  ...overrideResponse,
});

export const getEggControllerHatchedResponseMock = (
  overrideResponse: Partial<HatchedResponseDto> = {},
): HatchedResponseDto => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha(20),
  hatchedPetId: faker.string.alpha(20),
  ...overrideResponse,
});

export const getBrEggControllerFindAllResponseMock = (): BrEggControllerFindAll200 => ({
  [faker.string.alphanumeric(5)]: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    eggId: faker.string.alpha(20),
    owner: {
      ...{
        userId: faker.string.alpha(20),
        name: faker.string.alpha(20),
        role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
        isBiz: faker.datatype.boolean(),
        status: faker.helpers.arrayElement([
          "pending",
          "active",
          "inactive",
          "suspended",
          "deleted",
        ] as const),
      },
    },
    species: faker.helpers.arrayElement(["CR", "LE", "FT", "KN", "LC", "GG"] as const),
    layingDate: faker.number.int({ min: undefined, max: undefined }),
    clutch: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    clutchOrder: faker.number.int({ min: undefined, max: undefined }),
    name: faker.string.alpha(20),
    desc: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
    hatchedPetId: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
    father: faker.helpers.arrayElement([
      {
        ...{
          petId: faker.string.alpha(20),
          owner: {
            ...{
              userId: faker.string.alpha(20),
              name: faker.string.alpha(20),
              role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
              isBiz: faker.datatype.boolean(),
              status: faker.helpers.arrayElement([
                "pending",
                "active",
                "inactive",
                "suspended",
                "deleted",
              ] as const),
            },
          },
          name: faker.string.alpha(20),
          species: faker.helpers.arrayElement(["CR", "LE", "FT", "KN", "LC", "GG"] as const),
          morphs: faker.helpers.arrayElement([
            Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
              faker.string.alpha(20),
            ),
            undefined,
          ]),
          traits: faker.helpers.arrayElement([
            Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
              faker.string.alpha(20),
            ),
            undefined,
          ]),
          sex: faker.helpers.arrayElement([
            faker.helpers.arrayElement(["M", "F", "N"] as const),
            undefined,
          ]),
          relationId: faker.number.int({ min: undefined, max: undefined }),
          status: faker.helpers.arrayElement([
            "pending",
            "approved",
            "rejected",
            "deleted",
            "cancelled",
          ] as const),
        },
      },
      undefined,
    ]),
    mother: faker.helpers.arrayElement([
      {
        ...{
          petId: faker.string.alpha(20),
          owner: {
            ...{
              userId: faker.string.alpha(20),
              name: faker.string.alpha(20),
              role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
              isBiz: faker.datatype.boolean(),
              status: faker.helpers.arrayElement([
                "pending",
                "active",
                "inactive",
                "suspended",
                "deleted",
              ] as const),
            },
          },
          name: faker.string.alpha(20),
          species: faker.helpers.arrayElement(["CR", "LE", "FT", "KN", "LC", "GG"] as const),
          morphs: faker.helpers.arrayElement([
            Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
              faker.string.alpha(20),
            ),
            undefined,
          ]),
          traits: faker.helpers.arrayElement([
            Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
              faker.string.alpha(20),
            ),
            undefined,
          ]),
          sex: faker.helpers.arrayElement([
            faker.helpers.arrayElement(["M", "F", "N"] as const),
            undefined,
          ]),
          relationId: faker.number.int({ min: undefined, max: undefined }),
          status: faker.helpers.arrayElement([
            "pending",
            "approved",
            "rejected",
            "deleted",
            "cancelled",
          ] as const),
        },
      },
      undefined,
    ]),
  })),
});

export const getAuthControllerGetTokenResponseMock = (
  overrideResponse: Partial<TokenResponseDto> = {},
): TokenResponseDto => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha(20),
  token: faker.string.alpha(20),
  ...overrideResponse,
});

export const getUserControllerGetUserProfileResponseMock = (
  overrideResponse: Partial<UserProfileDto> = {},
): UserProfileDto => ({
  userId: faker.string.alpha(20),
  name: faker.string.alpha(20),
  email: faker.string.alpha(20),
  role: faker.helpers.arrayElement(["user", "breeder", "admin"] as const),
  isBiz: faker.datatype.boolean(),
  provider: faker.helpers.arrayElement(["kakao", "google", "naver", "apple"] as const),
  status: faker.helpers.arrayElement([
    "pending",
    "active",
    "inactive",
    "suspended",
    "deleted",
  ] as const),
  createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
  ...overrideResponse,
});

export const getUserControllerCreateInitUserInfoResponseMock = (
  overrideResponse: Partial<CommonResponseDto> = {},
): CommonResponseDto => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha(20),
  ...overrideResponse,
});

export const getPetControllerFindAllMockHandler = (
  overrideResponse?:
    | PetControllerFindAll200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PetControllerFindAll200> | PetControllerFindAll200),
) => {
  return http.get("*/api/v1/pet", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPetControllerFindAllResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getPetControllerCreateMockHandler = (
  overrideResponse?:
    | CommonResponseDto
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<CommonResponseDto> | CommonResponseDto),
) => {
  return http.post("*/api/v1/pet", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPetControllerCreateResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getPetControllerGetPetsWithChildrenMockHandler = (
  overrideResponse?:
    | PetControllerGetPetsWithChildren200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PetControllerGetPetsWithChildren200> | PetControllerGetPetsWithChildren200),
) => {
  return http.get("*/api/v1/pet/children", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPetControllerGetPetsWithChildrenResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getPetControllerFindOneMockHandler = (
  overrideResponse?:
    | PetDto
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PetDto> | PetDto),
) => {
  return http.get("*/api/v1/pet/:petId", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPetControllerFindOneResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getPetControllerUpdateMockHandler = (
  overrideResponse?:
    | CommonResponseDto
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<CommonResponseDto> | CommonResponseDto),
) => {
  return http.patch("*/api/v1/pet/:petId", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPetControllerUpdateResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getPetControllerDeleteMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
) => {
  return http.delete("*/api/v1/pet/:petId", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });
};

export const getParentControllerFindParentMockHandler = (
  overrideResponse?:
    | ParentDto
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ParentDto> | ParentDto),
) => {
  return http.get("*/api/v1/parent/:petId", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getParentControllerFindParentResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getParentControllerCreateParentMockHandler = (
  overrideResponse?:
    | CommonResponseDto
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<CommonResponseDto> | CommonResponseDto),
) => {
  return http.post("*/api/v1/parent/:petId", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getParentControllerCreateParentResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getParentControllerUpdateParentRequestMockHandler = (
  overrideResponse?:
    | CommonResponseDto
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<CommonResponseDto> | CommonResponseDto),
) => {
  return http.patch("*/api/v1/parent/update", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getParentControllerUpdateParentRequestResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getParentControllerDeleteParentMockHandler = (
  overrideResponse?:
    | CommonResponseDto
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<CommonResponseDto> | CommonResponseDto),
) => {
  return http.delete("*/api/v1/parent/delete/:relationId", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getParentControllerDeleteParentResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getUserNotificationControllerFindAllMockHandler = (
  overrideResponse?:
    | UserNotificationControllerFindAll200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UserNotificationControllerFindAll200> | UserNotificationControllerFindAll200),
) => {
  return http.get("*/api/v1/user-notification", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getUserNotificationControllerFindAllResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getUserNotificationControllerCreateMockHandler = (
  overrideResponse?:
    | CommonResponseDto
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<CommonResponseDto> | CommonResponseDto),
) => {
  return http.post("*/api/v1/user-notification", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getUserNotificationControllerCreateResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getUserNotificationControllerUpdateMockHandler = (
  overrideResponse?:
    | CommonResponseDto
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<CommonResponseDto> | CommonResponseDto),
) => {
  return http.patch("*/api/v1/user-notification", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getUserNotificationControllerUpdateResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getUserNotificationControllerDeleteMockHandler = (
  overrideResponse?:
    | CommonResponseDto
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<CommonResponseDto> | CommonResponseDto),
) => {
  return http.delete("*/api/v1/user-notification", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getUserNotificationControllerDeleteResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getBrPetControllerFindAllMockHandler = (
  overrideResponse?:
    | BrPetControllerFindAll200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<BrPetControllerFindAll200> | BrPetControllerFindAll200),
) => {
  return http.get("*/api/v1/br/pet", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getBrPetControllerFindAllResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getEggControllerFindOneMockHandler = (
  overrideResponse?:
    | EggDto
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<EggDto> | EggDto),
) => {
  return http.get("*/api/v1/egg/:eggId", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getEggControllerFindOneResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getEggControllerUpdateMockHandler = (
  overrideResponse?:
    | CommonResponseDto
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<CommonResponseDto> | CommonResponseDto),
) => {
  return http.patch("*/api/v1/egg/:eggId", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getEggControllerUpdateResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getEggControllerDeleteMockHandler = (
  overrideResponse?:
    | CommonResponseDto
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<CommonResponseDto> | CommonResponseDto),
) => {
  return http.delete("*/api/v1/egg/:eggId", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getEggControllerDeleteResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getEggControllerCreateMockHandler = (
  overrideResponse?:
    | CommonResponseDto
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<CommonResponseDto> | CommonResponseDto),
) => {
  return http.post("*/api/v1/egg", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getEggControllerCreateResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getEggControllerHatchedMockHandler = (
  overrideResponse?:
    | HatchedResponseDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<HatchedResponseDto> | HatchedResponseDto),
) => {
  return http.get("*/api/v1/egg/:eggId/hatched", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getEggControllerHatchedResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getBrEggControllerFindAllMockHandler = (
  overrideResponse?:
    | BrEggControllerFindAll200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<BrEggControllerFindAll200> | BrEggControllerFindAll200),
) => {
  return http.get("*/api/v1/br/egg", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getBrEggControllerFindAllResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getAuthControllerKakaoLoginMockHandler = (
  overrideResponse?:
    | unknown
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<unknown> | unknown),
) => {
  return http.get("*/api/auth/sign-in/kakao", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });
};

export const getAuthControllerGoogleLoginMockHandler = (
  overrideResponse?:
    | unknown
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<unknown> | unknown),
) => {
  return http.get("*/api/auth/sign-in/google", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });
};

export const getAuthControllerGetTokenMockHandler = (
  overrideResponse?:
    | TokenResponseDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<TokenResponseDto> | TokenResponseDto),
) => {
  return http.get("*/api/auth/token", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getAuthControllerGetTokenResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getAuthControllerSignOutMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
) => {
  return http.post("*/api/auth/sign-out", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });
};

export const getAuthControllerDeleteAccountMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
) => {
  return http.post("*/api/auth/delete-account", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });
};

export const getUserControllerGetUserProfileMockHandler = (
  overrideResponse?:
    | UserProfileDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UserProfileDto> | UserProfileDto),
) => {
  return http.get("*/api/v1/user/profile", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getUserControllerGetUserProfileResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getUserControllerCreateInitUserInfoMockHandler = (
  overrideResponse?:
    | CommonResponseDto
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<CommonResponseDto> | CommonResponseDto),
) => {
  return http.post("*/api/v1/user/init-info", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getUserControllerCreateInitUserInfoResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};
export const getProjectDaepaAPIMock = () => [
  getPetControllerFindAllMockHandler(),
  getPetControllerCreateMockHandler(),
  getPetControllerGetPetsWithChildrenMockHandler(),
  getPetControllerFindOneMockHandler(),
  getPetControllerUpdateMockHandler(),
  getPetControllerDeleteMockHandler(),
  getParentControllerFindParentMockHandler(),
  getParentControllerCreateParentMockHandler(),
  getParentControllerUpdateParentRequestMockHandler(),
  getParentControllerDeleteParentMockHandler(),
  getUserNotificationControllerFindAllMockHandler(),
  getUserNotificationControllerCreateMockHandler(),
  getUserNotificationControllerUpdateMockHandler(),
  getUserNotificationControllerDeleteMockHandler(),
  getBrPetControllerFindAllMockHandler(),
  getEggControllerFindOneMockHandler(),
  getEggControllerUpdateMockHandler(),
  getEggControllerDeleteMockHandler(),
  getEggControllerCreateMockHandler(),
  getEggControllerHatchedMockHandler(),
  getBrEggControllerFindAllMockHandler(),
  getAuthControllerKakaoLoginMockHandler(),
  getAuthControllerGoogleLoginMockHandler(),
  getAuthControllerGetTokenMockHandler(),
  getAuthControllerSignOutMockHandler(),
  getAuthControllerDeleteAccountMockHandler(),
  getUserControllerGetUserProfileMockHandler(),
  getUserControllerCreateInitUserInfoMockHandler(),
];
