/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  CreatePetDto,
  CreateUserNotificationDto,
  DeleteParentDto,
  PetControllerFindAllParams,
  UpdateParentDto,
  UpdatePetDto,
  UpdateUserNotificationDto,
  UserNotificationControllerFindAllParams,
} from "../model";

import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";

import type { PetControllerFindAll200, PetDto } from "../model";

export const petControllerFindAll = <TData = AxiosResponse<PetControllerFindAll200>>(
  params?: PetControllerFindAllParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`http://localhost:4000/api/v1/pet`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const petControllerCreate = <TData = AxiosResponse<void>>(
  createPetDto: CreatePetDto,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`http://localhost:4000/api/v1/pet`, createPetDto, options);
};

export const petControllerFindOne = <TData = AxiosResponse<PetDto>>(
  petId: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`http://localhost:4000/api/v1/pet/${petId}`, options);
};

export const petControllerUpdate = <TData = AxiosResponse<void>>(
  petId: string,
  updatePetDto: UpdatePetDto,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.patch(`http://localhost:4000/api/v1/pet/${petId}`, updatePetDto, options);
};

export const petControllerDelete = <TData = AxiosResponse<void>>(
  petId: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.delete(`http://localhost:4000/api/v1/pet/${petId}`, options);
};

export const parentControllerCreateParent = <TData = AxiosResponse<void>>(
  petId: string,
  updateParentDto: UpdateParentDto,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(
    `http://localhost:4000/api/v1/parent/update/${petId}`,
    updateParentDto,
    options,
  );
};

export const parentControllerDeleteParent = <TData = AxiosResponse<void>>(
  petId: string,
  deleteParentDto: DeleteParentDto,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(
    `http://localhost:4000/api/v1/parent/delete/${petId}`,
    deleteParentDto,
    options,
  );
};

export const userNotificationControllerFindAll = <TData = AxiosResponse<void>>(
  params?: UserNotificationControllerFindAllParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`http://localhost:4000/api/v1/user-notification`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const userNotificationControllerCreate = <TData = AxiosResponse<void>>(
  createUserNotificationDto: CreateUserNotificationDto,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(
    `http://localhost:4000/api/v1/user-notification`,
    createUserNotificationDto,
    options,
  );
};

export const userNotificationControllerUpdate = <TData = AxiosResponse<void>>(
  updateUserNotificationDto: UpdateUserNotificationDto,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.patch(
    `http://localhost:4000/api/v1/user-notification`,
    updateUserNotificationDto,
    options,
  );
};

export type PetControllerFindAllResult = AxiosResponse<PetControllerFindAll200>;
export type PetControllerCreateResult = AxiosResponse<void>;
export type PetControllerFindOneResult = AxiosResponse<PetDto>;
export type PetControllerUpdateResult = AxiosResponse<void>;
export type PetControllerDeleteResult = AxiosResponse<void>;
export type ParentControllerCreateParentResult = AxiosResponse<void>;
export type ParentControllerDeleteParentResult = AxiosResponse<void>;
export type UserNotificationControllerFindAllResult = AxiosResponse<void>;
export type UserNotificationControllerCreateResult = AxiosResponse<void>;
export type UserNotificationControllerUpdateResult = AxiosResponse<void>;

export const getPetControllerFindAllResponseMock = (
  overrideResponse: Partial<PetControllerFindAll200> = {},
): PetControllerFindAll200 => ({
  data: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    petId: faker.string.alpha(20),
    ownerId: faker.string.alpha(20),
    name: faker.string.alpha(20),
    species: {},
    morphs: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
        faker.string.alpha(20),
      ),
      undefined,
    ]),
    traits: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
        faker.string.alpha(20),
      ),
      undefined,
    ]),
    sex: faker.helpers.arrayElement([{}, undefined]),
  })),
  meta: {
    page: faker.number.int({ min: undefined, max: undefined }),
    itemPerPage: faker.number.int({ min: undefined, max: undefined }),
    totalCount: faker.number.int({ min: undefined, max: undefined }),
    totalPage: faker.number.int({ min: undefined, max: undefined }),
    hasPreviousPage: faker.datatype.boolean(),
    hasNextPage: faker.datatype.boolean(),
  },
  ...overrideResponse,
});

export const getPetControllerFindOneResponseMock = (
  overrideResponse: Partial<PetDto> = {},
): PetDto => ({
  petId: faker.string.alpha(20),
  ownerId: faker.string.alpha(20),
  name: faker.string.alpha(20),
  species: {},
  morphs: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
      faker.string.alpha(20),
    ),
    undefined,
  ]),
  traits: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
      faker.string.alpha(20),
    ),
    undefined,
  ]),
  birthdate: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  growth: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  sex: faker.helpers.arrayElement([{}, undefined]),
  weight: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  foods: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
      faker.string.alpha(20),
    ),
    undefined,
  ]),
  desc: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  father: faker.helpers.arrayElement([
    {
      ...{
        petId: faker.string.alpha(20),
        ownerId: faker.string.alpha(20),
        name: faker.string.alpha(20),
        species: {},
        morphs: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        traits: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        sex: faker.helpers.arrayElement([{}, undefined]),
      },
    },
    undefined,
  ]),
  mother: faker.helpers.arrayElement([
    {
      ...{
        petId: faker.string.alpha(20),
        ownerId: faker.string.alpha(20),
        name: faker.string.alpha(20),
        species: {},
        morphs: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        traits: faker.helpers.arrayElement([
          Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha(20),
          ),
          undefined,
        ]),
        sex: faker.helpers.arrayElement([{}, undefined]),
      },
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getPetControllerFindAllMockHandler = (
  overrideResponse?:
    | PetControllerFindAll200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PetControllerFindAll200> | PetControllerFindAll200),
) => {
  return http.get("*/api/v1/pet", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPetControllerFindAllResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getPetControllerCreateMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
) => {
  return http.post("*/api/v1/pet", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 201 });
  });
};

export const getPetControllerFindOneMockHandler = (
  overrideResponse?:
    | PetDto
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PetDto> | PetDto),
) => {
  return http.get("*/api/v1/pet/:petId", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPetControllerFindOneResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getPetControllerUpdateMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<void> | void),
) => {
  return http.patch("*/api/v1/pet/:petId", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });
};

export const getPetControllerDeleteMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
) => {
  return http.delete("*/api/v1/pet/:petId", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });
};

export const getParentControllerCreateParentMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
) => {
  return http.post("*/api/v1/parent/update/:petId", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 201 });
  });
};

export const getParentControllerDeleteParentMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
) => {
  return http.post("*/api/v1/parent/delete/:petId", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 201 });
  });
};

export const getUserNotificationControllerFindAllMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
) => {
  return http.get("*/api/v1/user-notification", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });
};

export const getUserNotificationControllerCreateMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
) => {
  return http.post("*/api/v1/user-notification", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 201 });
  });
};

export const getUserNotificationControllerUpdateMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<void> | void),
) => {
  return http.patch("*/api/v1/user-notification", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });
};
export const getProjectDaepaAPIMock = () => [
  getPetControllerFindAllMockHandler(),
  getPetControllerCreateMockHandler(),
  getPetControllerFindOneMockHandler(),
  getPetControllerUpdateMockHandler(),
  getPetControllerDeleteMockHandler(),
  getParentControllerCreateParentMockHandler(),
  getParentControllerDeleteParentMockHandler(),
  getUserNotificationControllerFindAllMockHandler(),
  getUserNotificationControllerCreateMockHandler(),
  getUserNotificationControllerUpdateMockHandler(),
];
