export const USER_NOTIFICATION_TYPE = {
  PARENT_REQUEST: 'PARENT_REQUEST',
  PARENT_ACCEPT: 'PARENT_ACCEPT',
  PARENT_REJECT: 'PARENT_REJECT',
  OWNER_TRANSFER: 'OWNER_TRANSFER',
  OWNER_ACCEPT: 'OWNER_ACCEPT',
  OWNER_REJECT: 'OWNER_REJECT',
} as const;

export const USER_NOTIFICATION_STATUS = {
  READ: 'READ',
  UNREAD: 'UNREAD',
  DELETED: 'DELETED',
} as const;
