export const USER_NOTIFICATION_TYPE = {
  PARENT_REQUEST: 'PARENT_REQUEST',
  PARENT_ACCEPT: 'PARENT_ACCEPT',
  PARENT_REJECT: 'PARENT_REJECT',
  OWNER_TRANSFER: 'OWNER_TRANSFER',
  OWNER_ACCEPT: 'OWNER_ACCEPT',
  OWNER_REJECT: 'OWNER_REJECT',
} as const;

export enum USER_NOTIFICATION_STATUS {
  READ = 'read',
  UNREAD = 'unread',
  DELETED = 'deleted',
}
