# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# react-native-config 환경변수를 xcconfig로 변환
system("#{__dir__}/scripts/set-env.sh")

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'mobile' do
  config = use_native_modules!

  # Firebase
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :new_arch_enabled => false
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # react-native-config 환경변수를 Pods xcconfig에 include
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        next unless build_config.base_configuration_reference
        xcconfig_path = build_config.base_configuration_reference.real_path
        next unless xcconfig_path && File.exist?(xcconfig_path)
        xcconfig_content = File.read(xcconfig_path)
        unless xcconfig_content.include?("Config.xcconfig")
          File.open(xcconfig_path, 'a') do |file|
            file.puts "\n#include \"../../../Config.xcconfig\""
          end
        end
      end
    end
  end
end
