import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { CompleteHatchingDto } from "@repo/api-client";
import { toast } from "sonner";
import { useState, useMemo } from "react";
import { format, isBefore } from "date-fns";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import NameInput from "../../components/NameInput";
import { cn } from "@/lib/utils";
import { useNameStore } from "../../store/name";
import { DUPLICATE_CHECK_STATUS } from "../../constants";
import CalendarSelect from "./CalendarSelect";
import { useCompleteHatching, generateAutoName } from "../hooks/useCompleteHatching";

/**
 * 해칭 완료 모달 Props
 */
export interface CompleteHatchingModalProps {
  /** 모달 열림 상태 */
  isOpen: boolean;
  /** 닫기 콜백 */
  onClose: () => void;
  /** 펫 ID */
  petId: string;
  /** 산란일 (해칭일 선택 범위 제한용) */
  layingDate: string;
  /** 클러치 번호 (자동 이름 생성용) */
  clutch?: number;
  /** 클러치 순서 (자동 이름 생성용) */
  clutchOrder?: number;
  /** 아버지 이름 (자동 이름 생성용) */
  fatherName?: string;
  /** 어머니 이름 (자동 이름 생성용) */
  motherName?: string;
  /** 완료 성공 시 콜백 (선택) */
  onCompleteSuccess?: () => void;
}

/**
 * 해칭 완료 모달
 *
 * @description
 * - Single Responsibility: UI 렌더링 + 폼 상태 관리만
 * - Open/Closed: onCompleteSuccess로 확장 가능
 * - Dependency Inversion: 비즈니스 로직은 useCompleteHatching에 위임
 *
 * @example
 * ```tsx
 * <CompleteHatchingModal
 *   isOpen={true}
 *   onClose={() => {}}
 *   petId="123"
 *   layingDate="2024-01-01"
 *   clutch={2}
 *   clutchOrder={1}
 *   fatherName="대박이"
 *   motherName="미미"
 * />
 * ```
 */
const CompleteHatchingModal = ({
  isOpen,
  onClose,
  petId,
  layingDate,
  clutch,
  clutchOrder,
  fatherName,
  motherName,
  onCompleteSuccess,
}: CompleteHatchingModalProps) => {
  const { duplicateCheckStatus } = useNameStore();

  // 자동 이름 생성 (useMemo로 최적화)
  const autoGeneratedName = useMemo(
    () =>
      generateAutoName({
        clutch,
        clutchOrder,
        fatherName,
        motherName,
      }) || "",
    [clutch, clutchOrder, fatherName, motherName],
  );

  // 폼 상태 관리
  const [formData, setFormData] = useState<CompleteHatchingDto>({
    hatchingDate: format(new Date(), "yyyy-MM-dd"),
    name: autoGeneratedName,
    desc: "",
  });

  // 비즈니스 로직은 커스텀 훅에 위임
  const { completeHatching, isPending } = useCompleteHatching({
    onSuccess: () => {
      onClose();
      onCompleteSuccess?.();
    },
  });

  /**
   * 폼 제출 핸들러 (검증 + 호출만)
   */
  const handleSubmit = async () => {
    // 클라이언트 검증
    if (!formData.hatchingDate) {
      toast.error("해칭일을 선택해주세요.");
      return;
    }

    if (!formData.name || duplicateCheckStatus !== DUPLICATE_CHECK_STATUS.AVAILABLE) {
      toast.error("이름을 입력하고 중복확인을 완료해주세요.");
      return;
    }

    // 비즈니스 로직 실행
    try {
      await completeHatching({ petId, formData });
    } catch {
      // 에러는 useCompleteHatching에서 처리됨
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="rounded-3xl sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>해칭 완료</DialogTitle>
        </DialogHeader>

        <div className="grid gap-4 py-4">
          {/* 해칭일 선택 */}
          <div className="grid grid-cols-4 items-center gap-4">
            <Label>해칭일*</Label>
            <div className="col-span-3">
              <CalendarSelect
                type="edit"
                triggerText={
                  formData.hatchingDate
                    ? format(new Date(formData.hatchingDate), "yyyy-MM-dd")
                    : "해칭일"
                }
                onConfirm={(date) => {
                  if (!date) return;
                  setFormData((prev) => ({ ...prev, hatchingDate: format(date, "yyyy-MM-dd") }));
                }}
                initialDate={formData.hatchingDate}
                disabled={(date) => isBefore(date, new Date(layingDate))}
              />
            </div>
          </div>

          {/* 이름 입력 */}
          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="clutch">이름*</Label>
            <div className="col-span-3 flex flex-col gap-1">
              <NameInput
                value={formData.name}
                placeholder="이름을 입력하세요"
                onChange={(e) => setFormData((prev) => ({ ...prev, name: e.target.value }))}
                className={cn(
                  "file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input shadow-xs flex h-10 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base outline-none transition-[color,box-shadow] file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
                  "aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
                  "text-blue-600",
                )}
                buttonClassName="h-10"
              />
            </div>
          </div>

          {/* 메모 입력 */}
          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="clutch">메모</Label>
            <div className="col-span-3 flex flex-col gap-1">
              <Textarea
                id="desc"
                placeholder="메모를 입력하세요"
                value={formData.desc}
                onChange={(e) => setFormData((prev) => ({ ...prev, desc: e.target.value }))}
              />
            </div>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose} disabled={isPending}>
            취소
          </Button>
          <Button onClick={handleSubmit} disabled={isPending}>
            {isPending ? "처리 중..." : "해칭 완료"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default CompleteHatchingModal;
