import { columns } from "./components/columns";
import DataTable from "./components/DataTable";
import { PET } from "./types";

async function getData(): Promise<PET[]> {
  // Fetch data from your API here.
  return [
    {
      id: "m5gr84i9",
      name: "대파",
      species: "레오파드",
      morph: ["파이어", "노멀", "할리퀸"],
      size: "베이비",
      sex: "수컷",
      weight: 10,
      mother: {
        id: "m5gr84i9",
        name: "어미파",
      },
      father: {
        id: "m5gr84i9",
        name: "아비파",
      },
      birthDate: "2025-01-01",
      photos: [],
      description: "레오파드 베이비",
      food: "귀뚜라미",
      canBreed: false,
      breedingCount: 0,
      pairing: {
        id: "m5gr84i9",
        name: "메이팅파",
      },
      saleInfo: "NFS", // 'NFS', 'SOLD', 'ON_SALE', 'ON_RESERVATION', 'TBD'
    },
    {
      id: "m5gr84i9",
      name: "쪽파",
      species: "크레스티드",
      morph: ["파이어", "노멀", "할리퀸"],
      size: "아성체",
      sex: "수컷",
      weight: 10,
      mother: {
        id: "m5gr84i9",
        name: "어미파",
      },
      father: {
        id: "m5gr84i9",
        name: "아비파",
      },
      birthDate: "2025-01-01",
      photos: [],
      description: "레오파드 아성체",
      food: "사료",
      canBreed: true,
      breedingCount: 5,
      pairing: {
        id: "m5gr84i9",
        name: "메이팅파",
      },
      saleInfo: "SOLD",
    },
    {
      id: "m5gr84i9",
      name: "대파",
      species: "리키에너스",
      morph: ["파이어", "노멀", "할리퀸"],
      size: "베이비",
      sex: "수컷",
      weight: 10,
      mother: {
        id: "m5gr84i9",
        name: "어미파",
      },
      father: {
        id: "m5gr84i9",
        name: "아비파",
      },
      birthDate: "2025-01-01",
      photos: [],
      description: "레오파드 베이비",
      food: "귀뚜라미",
      canBreed: false,
      breedingCount: 0,
      pairing: {
        id: "m5gr84i9",
        name: "메이팅파",
      },
      saleInfo: "ON_RESERVATION",
    },
    {
      id: "m5gr84i9",
      name: "쪽파",
      species: "차화",
      morph: ["파이어", "노멀", "할리퀸"],
      size: "베이비",
      sex: "수컷",
      weight: 10,
      mother: {
        id: "m5gr84i9",
        name: "어미파",
      },
      father: {
        id: "m5gr84i9",
        name: "아비파",
      },
      birthDate: "2025-01-01",
      photos: [],
      description: "레오파드 베이비",
      food: "귀뚜라미",
      canBreed: false,
      breedingCount: 0,
      pairing: {
        id: "m5gr84i9",
        name: "메이팅파",
      },
      saleInfo: "NFS", // 'NFS', 'SOLD', 'ON_SALE', 'ON_RESERVATION', 'TBD'
    },
    {
      id: "m5gr84i9",
      name: "양파",
      species: "가고일",
      morph: ["파이어", "노멀", "할리퀸"],
      size: "아성체",
      sex: "수컷",
      weight: 10,
      mother: {
        id: "m5gr84i9",
        name: "어미파",
      },
      father: {
        id: "m5gr84i9",
        name: "아비파",
      },
      birthDate: "2025-01-01",
      photos: [],
      description: "레오파드 아성체",
      food: "사료",
      canBreed: true,
      breedingCount: 5,
      pairing: {
        id: "m5gr84i9",
        name: "메이팅파",
      },
      saleInfo: "SOLD",
    },
    {
      id: "m5gr84i9",
      name: "가지",
      species: "펫테일",
      morph: ["파이어", "노멀", "할리퀸"],
      size: "베이비",
      sex: "수컷",
      weight: 10,
      mother: {
        id: "m5gr84i9",
        name: "어미파",
      },
      father: {
        id: "m5gr84i9",
        name: "아비파",
      },
      birthDate: "2025-01-01",
      photos: [],
      description: "레오파드 베이비",
      food: "귀뚜라미",
      canBreed: false,
      breedingCount: 0,
      pairing: {
        id: "m5gr84i9",
        name: "메이팅파",
      },
      saleInfo: "ON_RESERVATION",
    },
    {
      id: "m5gr84i9",
      name: "대파",
      species: "비어디 드래곤",
      morph: ["파이어", "노멀", "할리퀸"],
      size: "베이비",
      sex: "수컷",
      weight: 10,
      mother: {
        id: "m5gr84i9",
        name: "어미파",
      },
      father: {
        id: "m5gr84i9",
        name: "아비파",
      },
      birthDate: "2025-01-01",
      photos: [],
      description: "레오파드 베이비",
      food: "귀뚜라미",
      canBreed: false,
      breedingCount: 0,
      pairing: {
        id: "m5gr84i9",
        name: "메이팅파",
      },
      saleInfo: "NFS", // 'NFS', 'SOLD', 'ON_SALE', 'ON_RESERVATION', 'TBD'
    },
    {
      id: "m5gr84i9",
      name: "대파",
      species: "피그미 다람쥐",
      morph: ["파이어", "노멀", "할리퀸"],
      size: "아성체",
      sex: "수컷",
      weight: 10,
      mother: {
        id: "m5gr84i9",
        name: "어미파",
      },
      father: {
        id: "m5gr84i9",
        name: "아비파",
      },
      birthDate: "2025-01-01",
      photos: [],
      description: "레오파드 아성체",
      food: "사료",
      canBreed: true,
      breedingCount: 5,
      pairing: {
        id: "m5gr84i9",
        name: "메이팅파",
      },
      saleInfo: "SOLD",
    },
    {
      id: "m5gr84i9",
      name: "대파",
      species: "피그미 다람쥐",
      morph: ["파이어", "노멀", "할리퀸"],
      size: "베이비",
      sex: "수컷",
      weight: 10,
      mother: {
        id: "m5gr84i9",
        name: "어미파",
      },
      father: {
        id: "m5gr84i9",
        name: "아비파",
      },
      birthDate: "2025-01-01",
      photos: [],
      description: "레오파드 베이비",
      food: "귀뚜라미",
      canBreed: false,
      breedingCount: 0,
      pairing: {
        id: "m5gr84i9",
        name: "메이팅파",
      },
      saleInfo: "ON_RESERVATION",
    },
    {
      id: "m5gr84i9",
      name: "대파",
      species: "레오파드",
      morph: ["파이어", "노멀", "할리퀸"],
      size: "베이비",
      sex: "수컷",
      weight: 10,
      mother: {
        id: "m5gr84i9",
        name: "어미파",
      },
      father: {
        id: "m5gr84i9",
        name: "아비파",
      },
      birthDate: "2025-01-01",
      photos: [],
      description: "레오파드 베이비",
      food: "귀뚜라미",
      canBreed: false,
      breedingCount: 0,
      pairing: {
        id: "m5gr84i9",
        name: "메이팅파",
      },
      saleInfo: "NFS", // 'NFS', 'SOLD', 'ON_SALE', 'ON_RESERVATION', 'TBD'
    },
    {
      id: "m5gr84i9",
      name: "대파",
      species: "레오파드",
      morph: ["파이어", "노멀", "할리퀸"],
      size: "아성체",
      sex: "수컷",
      weight: 10,
      mother: {
        id: "m5gr84i9",
        name: "어미파",
      },
      father: {
        id: "m5gr84i9",
        name: "아비파",
      },
      birthDate: "2025-01-01",
      photos: [],
      description: "레오파드 아성체",
      food: "사료",
      canBreed: true,
      breedingCount: 5,
      pairing: {
        id: "m5gr84i9",
        name: "메이팅파",
      },
      saleInfo: "SOLD",
    },
    {
      id: "m5gr84i9",
      name: "대파",
      species: "레오파드",
      morph: ["파이어", "노멀", "할리퀸"],
      size: "베이비",
      sex: "수컷",
      weight: 10,
      mother: {
        id: "m5gr84i9",
        name: "어미파",
      },
      father: {
        id: "m5gr84i9",
        name: "아비파",
      },
      birthDate: "2025-01-01",
      photos: [],
      description: "레오파드 베이비",
      food: "귀뚜라미",
      canBreed: false,
      breedingCount: 0,
      pairing: {
        id: "m5gr84i9",
        name: "메이팅파",
      },
      saleInfo: "ON_RESERVATION",
    },
    {
      id: "m5gr84i9",
      name: "대파",
      species: "레오파드",
      morph: ["파이어", "노멀", "할리퀸"],
      size: "베이비",
      sex: "수컷",
      weight: 10,
      mother: {
        id: "m5gr84i9",
        name: "어미파",
      },
      father: {
        id: "m5gr84i9",
        name: "아비파",
      },
      birthDate: "2025-01-01",
      photos: [],
      description: "레오파드 베이비",
      food: "귀뚜라미",
      canBreed: false,
      breedingCount: 0,
      pairing: {
        id: "m5gr84i9",
        name: "메이팅파",
      },
      saleInfo: "NFS", // 'NFS', 'SOLD', 'ON_SALE', 'ON_RESERVATION', 'TBD'
    },
    {
      id: "m5gr84i9",
      name: "대파",
      species: "레오파드",
      morph: ["파이어", "노멀", "할리퀸"],
      size: "아성체",
      sex: "수컷",
      weight: 10,
      mother: {
        id: "m5gr84i9",
        name: "어미파",
      },
      father: {
        id: "m5gr84i9",
        name: "아비파",
      },
      birthDate: "2025-01-01",
      photos: [],
      description: "레오파드 아성체",
      food: "사료",
      canBreed: true,
      breedingCount: 5,
      pairing: {
        id: "m5gr84i9",
        name: "메이팅파",
      },
      saleInfo: "SOLD",
    },
    {
      id: "m5gr84i9",
      name: "대파",
      species: "레오파드",
      morph: ["파이어", "노멀", "할리퀸"],
      size: "베이비",
      sex: "수컷",
      weight: 10,
      mother: {
        id: "m5gr84i9",
        name: "어미파",
      },
      father: {
        id: "m5gr84i9",
        name: "아비파",
      },
      birthDate: "2025-01-01",
      photos: [],
      description: "레오파드 베이비",
      food: "귀뚜라미",
      canBreed: false,
      breedingCount: 0,
      pairing: {
        id: "m5gr84i9",
        name: "메이팅파",
      },
      saleInfo: "ON_RESERVATION",
    },
  ];
}

export default async function DemoPage() {
  const data = await getData();

  return (
    <div className="container mx-auto py-10">
      <DataTable columns={columns} data={data} />
    </div>
  );
}
