/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 작성자 이메일
 * @nullable
 */
export type AdminInquiryDtoUserEmail = { [key: string]: unknown } | null;
