/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { AdminInquiryDtoStatus } from "./adminInquiryDtoStatus";

export interface AdminInquiryDto {
  /** 문의 ID */
  id: number;
  /** 문의 내용 */
  content: string;
  /** 문의 상태 */
  status: AdminInquiryDtoStatus;
  /**
   * 관리자 답변
   * @nullable
   */
  answer: string | null;
  /**
   * 답변 시각
   * @nullable
   */
  answeredAt: string | null;
  /** 문의 작성 시각 */
  createdAt: string;
  /** 작성자 userId */
  userId: string;
  /**
   * 작성자 이름
   * @nullable
   */
  userName: string | null;
  /**
   * 작성자 이메일
   * @nullable
   */
  userEmail: string | null;
}
