/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { AdoptionDto } from "./adoptionDto";
import type { PageMetaDto } from "./pageMetaDto";

export type AdoptionControllerGetAllAdoptions200 = {
  data: AdoptionDto[];
  meta: PageMetaDto;
};
