/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type AdoptionHistoryControllerGetAllAdoptionsMethodItem =
  (typeof AdoptionHistoryControllerGetAllAdoptionsMethodItem)[keyof typeof AdoptionHistoryControllerGetAllAdoptionsMethodItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdoptionHistoryControllerGetAllAdoptionsMethodItem = {
  PICKUP: "PICKUP",
  DELIVERY: "DELIVERY",
  WHOLESALE: "WHOLESALE",
  EXPORT: "EXPORT",
} as const;
