/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 거래 방식
 */
export type AdoptionHistoryDtoMethod =
  (typeof AdoptionHistoryDtoMethod)[keyof typeof AdoptionHistoryDtoMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdoptionHistoryDtoMethod = {
  PICKUP: "PICKUP",
  DELIVERY: "DELIVERY",
  WHOLESALE: "WHOLESALE",
  EXPORT: "EXPORT",
} as const;
