/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type AdoptionControllerGetAllAdoptionsOrder =
  (typeof AdoptionControllerGetAllAdoptionsOrder)[keyof typeof AdoptionControllerGetAllAdoptionsOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdoptionControllerGetAllAdoptionsOrder = {
  ASC: "ASC",
  DESC: "DESC",
} as const;
