/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { AdoptionControllerGetAllAdoptionsOrder } from "./adoptionControllerGetAllAdoptionsOrder";
import type { AdoptionControllerGetAllAdoptionsSpecies } from "./adoptionControllerGetAllAdoptionsSpecies";
import type { AdoptionControllerGetAllAdoptionsStatus } from "./adoptionControllerGetAllAdoptionsStatus";

export type AdoptionControllerGetAllAdoptionsParams = {
  /**
   * 정렬 순서
   */
  order?: AdoptionControllerGetAllAdoptionsOrder;
  /**
   * 페이지 번호
   */
  page?: number;
  /**
   * 페이지당 항목 수
   */
  itemPerPage?: number;
  /**
   * 검색 키워드
   */
  keyword?: string;
  /**
   * 펫 종
   */
  species?: AdoptionControllerGetAllAdoptionsSpecies;
  /**
   * 펫 판매 상태
   */
  status?: AdoptionControllerGetAllAdoptionsStatus;
};
