/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { AdoptionControllerGetAllAdoptionsOrder } from "./adoptionControllerGetAllAdoptionsOrder";
import type { AdoptionControllerGetAllAdoptionsSpecies } from "./adoptionControllerGetAllAdoptionsSpecies";
import type { AdoptionControllerGetAllAdoptionsSex } from "./adoptionControllerGetAllAdoptionsSex";
import type { AdoptionControllerGetAllAdoptionsStatus } from "./adoptionControllerGetAllAdoptionsStatus";
import type { AdoptionControllerGetAllAdoptionsGrowth } from "./adoptionControllerGetAllAdoptionsGrowth";

export type AdoptionControllerGetAllAdoptionsParams = {
  /**
   * 정렬 순서
   */
  order?: AdoptionControllerGetAllAdoptionsOrder;
  /**
   * 페이지 번호
   */
  page?: number;
  /**
   * 페이지당 항목 수
   */
  itemPerPage?: number;
  /**
   * 검색 키워드 (이름, 설명 등)
   */
  keyword?: string;
  /**
   * 펫 종
   */
  species?: AdoptionControllerGetAllAdoptionsSpecies;
  /**
   * 펫 성별
   */
  sex?: AdoptionControllerGetAllAdoptionsSex;
  /**
   * 펫 공개 여부
   */
  isPublic?: number;
  /**
   * 펫 최소 생년월일
   */
  startYmd?: string;
  /**
   * 펫 최대 생년월일
   */
  endYmd?: string;
  /**
   * 펫 모프
   */
  morphs?: string[];
  /**
   * 펫 형질
   */
  traits?: string[];
  /**
   * 펫 먹이
   */
  foods?: string;
  /**
   * 판매 상태
   */
  status?: AdoptionControllerGetAllAdoptionsStatus;
  /**
   * 펫 성장단계
   */
  growth?: AdoptionControllerGetAllAdoptionsGrowth;
};
