/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 분양 상태
 */
export type AdoptionSummaryDtoStatus =
  (typeof AdoptionSummaryDtoStatus)[keyof typeof AdoptionSummaryDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdoptionSummaryDtoStatus = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;
