/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { AdoptionDtoLocation } from "./adoptionDtoLocation";
import type { AdoptionDtoStatus } from "./adoptionDtoStatus";
import type { UserProfilePublicDto } from "./userProfilePublicDto";
import type { PetSummaryWithoutOwnerDto } from "./petSummaryWithoutOwnerDto";

export interface AdoptionDto {
  /** 분양 ID */
  adoptionId: string;
  /** 펫 ID */
  petId: string;
  /** 분양 가격 */
  price?: number;
  /** 분양 날짜 */
  adoptionDate?: string;
  /** 메모 */
  memo?: string;
  /** 분양 위치 */
  location?: AdoptionDtoLocation;
  /** 펫 판매 상태 */
  status: AdoptionDtoStatus;
  /** 분양자 정보 */
  seller: UserProfilePublicDto;
  /** 입양자 정보 */
  buyer?: UserProfilePublicDto;
  /** 펫 정보 */
  pet: PetSummaryWithoutOwnerDto;
}
