/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type AdoptionControllerGetAllAdoptionsGrowth =
  (typeof AdoptionControllerGetAllAdoptionsGrowth)[keyof typeof AdoptionControllerGetAllAdoptionsGrowth];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdoptionControllerGetAllAdoptionsGrowth = {
  EGG: "EGG",
  BABY: "BABY",
  JUVENILE: "JUVENILE",
  PRE_ADULT: "PRE_ADULT",
  ADULT: "ADULT",
  DEAD: "DEAD",
} as const;
