/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type AdoptionControllerGetAdoptionByPetIdParams = {
  /**
   * 비활성 상태의 분양 정보도 포함할지 여부
   */
  includeInactive?: string;
};
