/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type AdoptionControllerGetAllAdoptionsStatus =
  (typeof AdoptionControllerGetAllAdoptionsStatus)[keyof typeof AdoptionControllerGetAllAdoptionsStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdoptionControllerGetAllAdoptionsStatus = {
  NFS: "NFS",
  ON_SALE: "ON_SALE",
  ON_RESERVATION: "ON_RESERVATION",
  SOLD: "SOLD",
} as const;
