/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 분양 방식
 * @nullable
 */
export type AdoptionCompleteDetailJsonMethod =
  | (typeof AdoptionCompleteDetailJsonMethod)[keyof typeof AdoptionCompleteDetailJsonMethod]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdoptionCompleteDetailJsonMethod = {
  PICKUP: "PICKUP",
  DELIVERY: "DELIVERY",
  WHOLESALE: "WHOLESALE",
  EXPORT: "EXPORT",
} as const;
