/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 분양 위치
 */
export type AdoptionDtoLocation = (typeof AdoptionDtoLocation)[keyof typeof AdoptionDtoLocation];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdoptionDtoLocation = {
  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
} as const;
