/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { AdoptionHistoryControllerGetAllAdoptionsOrder } from "./adoptionHistoryControllerGetAllAdoptionsOrder";
import type { AdoptionHistoryControllerGetAllAdoptionsSpecies } from "./adoptionHistoryControllerGetAllAdoptionsSpecies";
import type { AdoptionHistoryControllerGetAllAdoptionsSexItem } from "./adoptionHistoryControllerGetAllAdoptionsSexItem";
import type { AdoptionHistoryControllerGetAllAdoptionsGrowthItem } from "./adoptionHistoryControllerGetAllAdoptionsGrowthItem";
import type { AdoptionHistoryControllerGetAllAdoptionsMethod } from "./adoptionHistoryControllerGetAllAdoptionsMethod";

export type AdoptionHistoryControllerGetAllAdoptionsParams = {
  /**
   * 정렬 순서
   */
  order?: AdoptionHistoryControllerGetAllAdoptionsOrder;
  /**
   * 페이지 번호
   */
  page?: number;
  /**
   * 페이지당 항목 수
   */
  itemPerPage?: number;
  /**
   * 검색 키워드
   */
  keyword?: string;
  /**
   * 펫 종
   */
  species?: AdoptionHistoryControllerGetAllAdoptionsSpecies;
  /**
   * 펫 모프
   */
  morphs?: string[];
  /**
   * 펫 형질
   */
  traits?: string[];
  /**
   * 펫 성별
   */
  sex?: AdoptionHistoryControllerGetAllAdoptionsSexItem[];
  /**
   * 펫 성장단계
   */
  growth?: AdoptionHistoryControllerGetAllAdoptionsGrowthItem[];
  /**
   * 분양 방식
   */
  method?: AdoptionHistoryControllerGetAllAdoptionsMethod;
  /**
   * 최소 분양 가격
   */
  minPrice?: number;
  /**
   * 최대 분양 가격
   */
  maxPrice?: number;
  /**
   * 최소 분양 날짜
   */
  startDate?: string;
  /**
   * 최대 분양 날짜
   */
  endDate?: string;
  /**
   * 부 개체 ID
   */
  fatherId?: string;
  /**
   * 모 개체 ID
   */
  motherId?: string;
};
