/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { AdoptionDtoStatus } from "./adoptionDtoStatus";
import type { AdoptionDtoReservedUser } from "./adoptionDtoReservedUser";

export interface AdoptionDto {
  /** 펫 ID */
  petId: string;
  /** 희망 분양가 */
  price?: number;
  /** 메모 */
  memo?: string;
  /** 생성일 */
  createdAt: string;
  /**
   * 분양 상태 (null이면 미지정)
   * @nullable
   */
  status: AdoptionDtoStatus;
  /**
   * 예약자 정보
   * @nullable
   */
  reservedUser?: AdoptionDtoReservedUser;
}
