/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 분양 방식
 */
export type AdoptionDtoMethod = (typeof AdoptionDtoMethod)[keyof typeof AdoptionDtoMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdoptionDtoMethod = {
  PICKUP: "PICKUP",
  DELIVERY: "DELIVERY",
  WHOLESALE: "WHOLESALE",
} as const;
