/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UserProfilePublicDto } from "./userProfilePublicDto";

/**
 * 예약자 정보
 * @nullable
 */
export type AdoptionDtoReservedUser = UserProfilePublicDto | null;
