/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { AdoptionControllerGetAllAdoptions200Data } from "./adoptionControllerGetAllAdoptions200Data";

export type AdoptionControllerGetAllAdoptions200 = {
  success: boolean;
  message: string;
  data: AdoptionControllerGetAllAdoptions200Data;
};
