/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type AdoptionHistoryControllerGetAllAdoptionsSexItem =
  (typeof AdoptionHistoryControllerGetAllAdoptionsSexItem)[keyof typeof AdoptionHistoryControllerGetAllAdoptionsSexItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdoptionHistoryControllerGetAllAdoptionsSexItem = {
  MALE: "M",
  FEMALE: "F",
  NON: "N",
} as const;
