/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 분양 상태
 */
export type AdoptionDtoStatus = (typeof AdoptionDtoStatus)[keyof typeof AdoptionDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdoptionDtoStatus = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;
