/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { AdoptionHistoryDtoMethod } from "./adoptionHistoryDtoMethod";
import type { UserProfilePublicDto } from "./userProfilePublicDto";
import type { PetAdoptionCompletedDto } from "./petAdoptionCompletedDto";

export interface AdoptionHistoryDto {
  /** 분양 이력 ID */
  id: number;
  /** 펫 ID */
  petId: string;
  /** 거래가 */
  price?: number;
  /** 분양 날짜 */
  adoptionDate?: string;
  /** 메모 */
  memo?: string;
  /** 거래 방식 */
  method?: AdoptionHistoryDtoMethod;
  /** 생성일 */
  createdAt: string;
  /** 분양자 정보 */
  seller?: UserProfilePublicDto;
  /** 입양자 정보 */
  buyer?: UserProfilePublicDto;
  /** 펫 정보 (스냅샷이 없으면 {}) */
  pet: PetAdoptionCompletedDto;
}
