/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetAdoptionCompletedDto } from "./petAdoptionCompletedDto";

/**
 * 펫 정보 (스냅샷이 없으면 {})
 */
export type AdoptionHistoryDtoPet = PetAdoptionCompletedDto;
