/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 펫 판매 상태
 */
export type AdoptionSummaryDtoStatus =
  (typeof AdoptionSummaryDtoStatus)[keyof typeof AdoptionSummaryDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdoptionSummaryDtoStatus = {
  NFS: "NFS",
  ON_SALE: "ON_SALE",
  ON_RESERVATION: "ON_RESERVATION",
  SOLD: "SOLD",
} as const;
