/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { NotificationSellerDto } from "./notificationSellerDto";
import type { NotificationAdoptionPetDto } from "./notificationAdoptionPetDto";
import type { AdoptionCompleteDetailJsonAdoptionDate } from "./adoptionCompleteDetailJsonAdoptionDate";
import type { AdoptionCompleteDetailJsonPrice } from "./adoptionCompleteDetailJsonPrice";
import type { AdoptionCompleteDetailJsonMethod } from "./adoptionCompleteDetailJsonMethod";

export interface AdoptionCompleteDetailJson {
  /** 메시지 */
  message?: string;
  /** 판매자 정보 */
  seller?: NotificationSellerDto;
  /** 개체 정보 (이름 + 썸네일) */
  pet?: NotificationAdoptionPetDto;
  /**
   * 분양 날짜
   * @nullable
   */
  adoptionDate?: AdoptionCompleteDetailJsonAdoptionDate;
  /**
   * 분양 가격
   * @nullable
   */
  price?: AdoptionCompleteDetailJsonPrice;
  /**
   * 분양 방식
   * @nullable
   */
  method?: AdoptionCompleteDetailJsonMethod;
}
