/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UserProfilePublicDto } from "./userProfilePublicDto";
import type { AdoptionDtoStatus } from "./adoptionDtoStatus";

export interface AdoptionDto {
  /** 분양 ID */
  adoptionId: string;
  /** 펫 ID */
  petId: string;
  /** 분양 가격 */
  price?: number;
  /** 분양 날짜 */
  adoptionDate?: string;
  /** 분양자 정보 */
  seller: UserProfilePublicDto;
  /** 입양자 정보 */
  buyer?: UserProfilePublicDto;
  /** 메모 */
  memo?: string;
  /** 거래 장소 */
  location?: string;
  /** 분양 상태 */
  status: AdoptionDtoStatus;
  /** 생성일 */
  createdAt: string;
  /** 수정일 */
  updatedAt: string;
}
