/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type AdoptionHistoryControllerGetAllAdoptionsMethod =
  (typeof AdoptionHistoryControllerGetAllAdoptionsMethod)[keyof typeof AdoptionHistoryControllerGetAllAdoptionsMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdoptionHistoryControllerGetAllAdoptionsMethod = {
  PICKUP: "PICKUP",
  DELIVERY: "DELIVERY",
  WHOLESALE: "WHOLESALE",
  EXPORT: "EXPORT",
} as const;
