/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface AnswerInquiryDto {
  /** 관리자 답변 내용 */
  answer: string;
}
