/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface AppleNativeLoginRequestDto {
  /** Apple identity token (JWT) */
  identityToken: string;
  /** Authorization code */
  authorizationCode?: string;
  /** 사용자 이메일(없을 수 있음) */
  email?: string;
  /** nonce(raw 또는 hashed) */
  nonce?: string;
  /** 닉네임 */
  name?: string;
  /** 사용자 유형 */
  isBiz?: boolean;
}
