/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { AuctionStateDtoStatus } from "./auctionStateDtoStatus";
import type { AuctionStateDtoHighestBidder } from "./auctionStateDtoHighestBidder";
import type { AuctionBidDto } from "./auctionBidDto";

export interface AuctionStateDto {
  auctionId: string;
  shareToken: string;
  petId: string;
  hostUserId: string;
  status: AuctionStateDtoStatus;
  startingPrice: number;
  minIncrement: number;
  extensionMinutes: number;
  startTimeMs: number;
  originalEndTimeMs: number;
  currentEndTimeMs: number;
  highestBid: number;
  /** @nullable */
  highestBidder: AuctionStateDtoHighestBidder;
  recentBids: AuctionBidDto[];
  serverNowMs: number;
  /** @nullable */
  finalPrice: number | null;
  /** @nullable */
  winnerUserId: string | null;
}
