/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { AuctionStateDto } from "./auctionStateDto";

/**
 * @nullable
 */
export type AuctionResponseDtoData = AuctionStateDto | null;
