/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type AuctionStateDtoStatus =
  (typeof AuctionStateDtoStatus)[keyof typeof AuctionStateDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuctionStateDtoStatus = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  ENDED: "ENDED",
  CANCELED: "CANCELED",
} as const;
