/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface AuctionBidDto {
  bidderUserId: string;
  /** @nullable */
  bidderNickname?: string | null;
  amount: number;
  serverTsMs: number;
  triggeredExtension: boolean;
}
