/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 다음 페이지 cursor (다음 호출 시 cursor 쿼리로 전달)
 * @nullable
 */
export type BidHistoryResponseDtoNextCursor = { [key: string]: unknown } | null;
