/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { BidHistoryItemDto } from "./bidHistoryItemDto";

export interface BidHistoryResponseDto {
  /** 성공 여부 */
  success: boolean;
  /** 메시지 */
  message: string;
  data: BidHistoryItemDto[];
  /**
   * 다음 페이지 cursor (다음 호출 시 cursor 쿼리로 전달)
   * @nullable
   */
  nextCursor: string | null;
}
