/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type BrAdoptionControllerGetAllAdoptionsStatus =
  (typeof BrAdoptionControllerGetAllAdoptionsStatus)[keyof typeof BrAdoptionControllerGetAllAdoptionsStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BrAdoptionControllerGetAllAdoptionsStatus = {
  NONE: "NONE",
  NFS: "NFS",
  ON_SALE: "ON_SALE",
  ON_RESERVATION: "ON_RESERVATION",
  SOLD: "SOLD",
  REFUNDED: "REFUNDED",
} as const;
