/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { BrAdoptionControllerGetAllAdoptionsOrder } from "./brAdoptionControllerGetAllAdoptionsOrder";
import type { BrAdoptionControllerGetAllAdoptionsSpecies } from "./brAdoptionControllerGetAllAdoptionsSpecies";
import type { BrAdoptionControllerGetAllAdoptionsSexItem } from "./brAdoptionControllerGetAllAdoptionsSexItem";
import type { BrAdoptionControllerGetAllAdoptionsGrowthItem } from "./brAdoptionControllerGetAllAdoptionsGrowthItem";
import type { BrAdoptionControllerGetAllAdoptionsMethod } from "./brAdoptionControllerGetAllAdoptionsMethod";

export type BrAdoptionControllerGetAllAdoptionsParams = {
  /**
   * 정렬 순서
   */
  order?: BrAdoptionControllerGetAllAdoptionsOrder;
  /**
   * 페이지 번호
   */
  page?: number;
  /**
   * 페이지당 항목 수
   */
  itemPerPage?: number;
  /**
   * 검색 키워드
   */
  keyword?: string;
  /**
   * 펫 종
   */
  species?: BrAdoptionControllerGetAllAdoptionsSpecies;
  /**
   * 펫 모프
   */
  morphs?: string[];
  /**
   * 펫 형질
   */
  traits?: string[];
  /**
   * 펫 성별
   */
  sex?: BrAdoptionControllerGetAllAdoptionsSexItem[];
  /**
   * 펫 성장단계
   */
  growth?: BrAdoptionControllerGetAllAdoptionsGrowthItem[];
  /**
   * 분양 방식
   */
  method?: BrAdoptionControllerGetAllAdoptionsMethod;
  /**
   * 최소 분양 가격
   */
  minPrice?: number;
  /**
   * 최대 분양 가격
   */
  maxPrice?: number;
  /**
   * 최소 분양 날짜
   */
  startDate?: string;
  /**
   * 최대 분양 날짜
   */
  endDate?: string;
  /**
   * 부 개체 ID
   */
  fatherId?: string;
  /**
   * 모 개체 ID
   */
  motherId?: string;
};
