/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { BreederPublicProfileDto } from "./breederPublicProfileDto";

export interface BreederPublicProfileResponseDto {
  /** 성공 여부 */
  success: boolean;
  /** 메시지 */
  message: string;
  /** 브리더 공개 프로필 */
  data: BreederPublicProfileDto;
}
