/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 연락처 (공개 설정 시)
 */
export type BreederPublicProfileDtoPhone = { [key: string]: unknown };
