/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { BreederPublicProfileDtoStatus } from "./breederPublicProfileDtoStatus";
import type { BreederPublicProfileDtoRole } from "./breederPublicProfileDtoRole";
import type { BreederPublicProfileDtoRealName } from "./breederPublicProfileDtoRealName";
import type { BreederPublicProfileDtoPhone } from "./breederPublicProfileDtoPhone";
import type { BreederPublicProfileDtoAddress } from "./breederPublicProfileDtoAddress";

export interface BreederPublicProfileDto {
  /** 유저 상태 */
  status: BreederPublicProfileDtoStatus;
  /** 회원 고유 ID */
  userId?: string;
  /** 회원 이름 */
  name?: string;
  /** 회원 역할 */
  role?: BreederPublicProfileDtoRole;
  /** 사업자 여부 */
  isBiz?: boolean;
  /** 공개 펫 수 */
  petCount: number;
  /** 실명/상호 (공개 설정 시) */
  realName?: BreederPublicProfileDtoRealName;
  /** 연락처 (공개 설정 시) */
  phone?: BreederPublicProfileDtoPhone;
  /** 주소 (공개 설정 시) */
  address?: BreederPublicProfileDtoAddress;
  /**
   * 배너 이미지 URL
   * @nullable
   */
  bannerImageUrl?: string | null;
}
