/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type BrEggControllerFindAllParams = {
  /**
   * 조회 범위 시작일
   */
  startYmd?: number;
  /**
   * 조회 범위 종료일
   */
  endYmd?: number;
};
