/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { BrMatingControllerFindAllOrder } from "./brMatingControllerFindAllOrder";

export type BrMatingControllerFindAllParams = {
  /**
   * 정렬 순서
   */
  order?: BrMatingControllerFindAllOrder;
  /**
   * 페이지 번호
   */
  page?: number;
  /**
   * 페이지당 항목 수
   */
  itemPerPage?: number;
};
