/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { BrMatingControllerFindAllOrder } from "./brMatingControllerFindAllOrder";
import type { BrMatingControllerFindAllSpecies } from "./brMatingControllerFindAllSpecies";
import type { BrMatingControllerFindAllEggStatus } from "./brMatingControllerFindAllEggStatus";

export type BrMatingControllerFindAllParams = {
  /**
   * 정렬 순서
   */
  order?: BrMatingControllerFindAllOrder;
  /**
   * 페이지 번호
   */
  page?: number;
  /**
   * 페이지당 항목 수
   */
  itemPerPage?: number;
  /**
   * 펫 종
   */
  species?: BrMatingControllerFindAllSpecies;
  /**
   * 펫 최소 생년월일
   */
  startYmd?: string;
  /**
   * 펫 최대 생년월일
   */
  endYmd?: string;
  /**
   * 아빠 펫 ID
   */
  fatherId?: string;
  /**
   * 엄마 펫 ID
   */
  motherId?: string;
  /**
   * 알 상태
   */
  eggStatus?: BrMatingControllerFindAllEggStatus;
};
