/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { BrPetControllerFindAllOrder } from "./brPetControllerFindAllOrder";
import type { BrPetControllerFindAllSpecies } from "./brPetControllerFindAllSpecies";
import type { BrPetControllerFindAllSex } from "./brPetControllerFindAllSex";
import type { BrPetControllerFindAllStatus } from "./brPetControllerFindAllStatus";
import type { BrPetControllerFindAllGrowth } from "./brPetControllerFindAllGrowth";

export type BrPetControllerFindAllParams = {
  /**
   * 정렬 순서
   */
  order?: BrPetControllerFindAllOrder;
  /**
   * 페이지 번호
   */
  page?: number;
  /**
   * 페이지당 항목 수
   */
  itemPerPage?: number;
  /**
   * 검색 키워드 (이름, 설명 등)
   */
  keyword?: string;
  /**
   * 펫 종
   */
  species?: BrPetControllerFindAllSpecies;
  /**
   * 펫 성별
   */
  sex?: BrPetControllerFindAllSex;
  /**
   * 펫 소유자 아이디
   */
  ownerId?: string;
  /**
   * 펫 공개 여부
   */
  isPublic?: boolean;
  /**
   * 펫 최소 몸무게
   */
  minWeight?: number;
  /**
   * 펫 최대 몸무게
   */
  maxWeight?: number;
  /**
   * 펫 최소 생년월일
   */
  minBirthdate?: number;
  /**
   * 펫 최대 생년월일
   */
  maxBirthdate?: number;
  /**
   * 펫 모프
   */
  morphs?: string[];
  /**
   * 펫 형질
   */
  traits?: string[];
  /**
   * 펫 먹이
   */
  foods?: string;
  /**
   * 판매 상태
   */
  status?: BrPetControllerFindAllStatus;
  /**
   * 펫 성장단계
   */
  growth?: BrPetControllerFindAllGrowth;
  /**
   * 타인 펫 포함 여부
   */
  includeOthers?: boolean;
};
