/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type BrPetControllerFindAllFilterType =
  (typeof BrPetControllerFindAllFilterType)[keyof typeof BrPetControllerFindAllFilterType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BrPetControllerFindAllFilterType = {
  ALL: "ALL",
  MY: "MY",
  NOT_MY: "NOT_MY",
} as const;
