/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { BrUserControllerGetUsersOrder } from "./brUserControllerGetUsersOrder";

export type BrUserControllerGetUsersParams = {
  /**
   * 정렬 순서
   */
  order?: BrUserControllerGetUsersOrder;
  /**
   * 페이지 번호
   */
  page?: number;
  /**
   * 페이지당 항목 수
   */
  itemPerPage?: number;
  /**
   * 검색 키워드
   */
  keyword?: string;
};
