/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type BrUserControllerGetUsersOrder =
  (typeof BrUserControllerGetUsersOrder)[keyof typeof BrUserControllerGetUsersOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BrUserControllerGetUsersOrder = {
  ASC: "ASC",
  DESC: "DESC",
} as const;
