/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { BulkCreatePetRowDto } from "./bulkCreatePetRowDto";

export interface BulkCreatePetDto {
  /** 개체 목록 */
  pets: BulkCreatePetRowDto[];
}
