/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 성별
 */
export type BulkCreatePetRowDtoSex =
  (typeof BulkCreatePetRowDtoSex)[keyof typeof BulkCreatePetRowDtoSex];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BulkCreatePetRowDtoSex = {
  M: "M",
  F: "F",
  N: "N",
} as const;
