/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface BulkCreatePetResultDto {
  /** 성공적으로 생성된 개체 수 */
  successCount: number;
  /** 생성된 개체의 petId 목록 */
  createdPetIds: string[];
}
