/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { BulkCreatePetRowDtoSpecies } from "./bulkCreatePetRowDtoSpecies";
import type { BulkCreatePetRowDtoSex } from "./bulkCreatePetRowDtoSex";
import type { BulkCreatePetRowDtoGrowth } from "./bulkCreatePetRowDtoGrowth";
import type { BulkCreatePetRowDtoAdoptionStatus } from "./bulkCreatePetRowDtoAdoptionStatus";
import type { PetImageItem } from "./petImageItem";

export interface BulkCreatePetRowDto {
  /** 개체 이름 */
  name: string;
  /** 종 */
  species: BulkCreatePetRowDtoSpecies;
  /** 성별 */
  sex?: BulkCreatePetRowDtoSex;
  /** 성장단계 */
  growth?: BulkCreatePetRowDtoGrowth;
  /** 해칭일 (yyyy-MM-dd) */
  hatchingDate?: string;
  /** 공개 여부 */
  isPublic?: boolean;
  /** 브리더펫 여부 */
  isBreeder?: boolean;
  /** 모프 */
  morphs?: string[];
  /** 형질 */
  traits?: string[];
  /** 먹이 */
  foods?: string[];
  /** 몸무게(g) */
  weight?: number;
  /** 분양상태 */
  adoptionStatus?: BulkCreatePetRowDtoAdoptionStatus;
  /** 부개체 이름 */
  fatherName?: string;
  /** 모개체 이름 */
  motherName?: string;
  /** 펫 이미지 (PENDING/* 키 사용 — 서버가 {petId}/*로 복사) */
  images?: PetImageItem[];
}
