/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { ChildPetDetailDtoType } from "./childPetDetailDtoType";
import type { UserProfilePublicDto } from "./userProfilePublicDto";
import type { ChildPetDetailDtoSpecies } from "./childPetDetailDtoSpecies";
import type { ChildPetDetailDtoSex } from "./childPetDetailDtoSex";
import type { ChildPetDetailDtoGrowth } from "./childPetDetailDtoGrowth";

export interface ChildPetDetailDto {
  /** 펫 아이디 */
  petId: string;
  /** 펫 타입(egg/pet) */
  type?: ChildPetDetailDtoType;
  /** 펫 주인 정보 */
  owner: UserProfilePublicDto;
  /** 펫 이름 */
  name?: string;
  /** 펫 종 */
  species: ChildPetDetailDtoSpecies;
  /** 펫 출생일 */
  hatchingDate?: string;
  /** 펫 공개 여부 */
  isPublic?: boolean;
  /** 브리더펫 여부 */
  isBreeder?: boolean;
  /** 펫 삭제 여부 */
  isDeleted?: boolean;
  /** 펫 성별(수컷, 암컷, 미구분) */
  sex?: ChildPetDetailDtoSex;
  /** 펫 모프 */
  morphs?: string[];
  /** 펫 형질 */
  traits?: string[];
  /** 펫 성장단계 */
  growth?: ChildPetDetailDtoGrowth;
  /** 펫 몸무게(g) */
  weight?: number;
}
