/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface CompleteHatchingDto {
  /** 펫 이름 */
  name?: string;
  /** 펫 출생일 */
  hatchingDate?: string;
  /** 펫 소개말 */
  desc?: string;
}
