/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 거래 방식
 * @nullable
 */
export type CompleteAdoptionDtoMethod =
  | (typeof CompleteAdoptionDtoMethod)[keyof typeof CompleteAdoptionDtoMethod]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompleteAdoptionDtoMethod = {
  PICKUP: "PICKUP",
  DELIVERY: "DELIVERY",
  WHOLESALE: "WHOLESALE",
  EXPORT: "EXPORT",
} as const;
