/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { CompleteAdoptionDtoMethod } from "./completeAdoptionDtoMethod";

export interface CompleteAdoptionDto {
  /**
   * 거래가
   * @nullable
   */
  price?: number | null;
  /**
   * 입양자 ID
   * @nullable
   */
  buyerId?: string | null;
  /**
   * 분양 날짜
   * @nullable
   */
  adoptionDate?: string | null;
  /**
   * 거래 방식
   * @nullable
   */
  method?: CompleteAdoptionDtoMethod;
  /**
   * 메모
   * @nullable
   */
  memo?: string | null;
}
