/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 펫 타입
 */
export type CreatePetDtoType = (typeof CreatePetDtoType)[keyof typeof CreatePetDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePetDtoType = {
  EGG: "EGG",
  PET: "PET",
} as const;
