/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 알 종
 */
export type CreateEggDtoSpecies = (typeof CreateEggDtoSpecies)[keyof typeof CreateEggDtoSpecies];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEggDtoSpecies = {
  CRESTED: "CR",
  LEOPARD: "LE",
  FATTAIL: "FT",
  KNOPTAIL: "KN",
  LEACH: "LC",
  GARGO: "GG",
} as const;
