/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 펫인지 알인지 여부
 */
export type CreateParentDtoType = (typeof CreateParentDtoType)[keyof typeof CreateParentDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateParentDtoType = {
  egg: "egg",
  pet: "pet",
} as const;
