/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface CreateEggHatchDto {
  /** 펫 이름 */
  name: string;
  /** 펫 모프 */
  morphs?: string[];
  /** 펫 형질 */
  traits?: string[];
  /** 펫 출생일 */
  birthdate?: number;
  /** 펫 몸무게(g) */
  weight?: number;
  /** 펫 먹이 */
  foods?: string[];
  /** 펫 소개말 */
  desc?: string;
}
