/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 알림 타입
 */
export type CreateUserNotificationDtoType =
  (typeof CreateUserNotificationDtoType)[keyof typeof CreateUserNotificationDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserNotificationDtoType = {
  PARENT_REQUEST: "parent_request",
  PARENT_ACCEPT: "parent_accept",
  PARENT_REJECT: "parent_reject",
  OWNER_TRANSFER: "owner_transfer",
  OWNER_ACCEPT: "owner_accept",
  OWNER_REJECT: "owner_reject",
} as const;
