/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface CreateAuctionDto {
  /** 경매 대상 펫 ID */
  petId: string;
  /**
   * 시작가 (원 단위)
   * @minimum 0
   */
  startingPrice: number;
  /**
   * 최소 입찰 단위 (원)
   * @minimum 100
   */
  minIncrement: number;
  /**
   * 연장 분 (1~10)
   * @minimum 1
   * @maximum 10
   */
  extensionMinutes: number;
  /** 시작 시각 ISO8601 */
  startTime: string;
  /** 종료 시각 ISO8601 */
  endTime: string;
}
