/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { CreateLayingDtoEggType } from "./createLayingDtoEggType";

export interface CreateLayingDto {
  /** Mating ID */
  matingId: number;
  /** Laying Date */
  layingDate: number;
  /** 알 상태 */
  eggType?: CreateLayingDtoEggType;
  /** 알 ID */
  eggId: string;
  /** 해칭 온도 */
  temperture?: number;
}
