/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 발송 상태
 */
export type CreateAnnouncementResponseDtoStatus =
  (typeof CreateAnnouncementResponseDtoStatus)[keyof typeof CreateAnnouncementResponseDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateAnnouncementResponseDtoStatus = {
  sending: "sending",
  sent: "sent",
  failed: "failed",
} as const;
