/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface CreateAnnouncementDto {
  /** 공지 제목 */
  title: string;
  /** 공지 내용 */
  body: string;
  /** 알림 클릭 시 이동 경로 */
  path?: string;
}
