/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { CreateParentDtoRole } from "./createParentDtoRole";

export interface CreateParentDto {
  /** 부모 ID */
  parentId: string;
  /** 부모 구분 */
  role: CreateParentDtoRole;
  /** 본인 소유 펫 여부 */
  isMyPet?: boolean;
  /** 알에서 펫 전환 상황인지 여부 */
  isEggToPet?: boolean;
  /** 부모 관계 요청 메시지 */
  message?: string;
}
