/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 부모 역할
 */
export type CreateParentDtoRole = (typeof CreateParentDtoRole)[keyof typeof CreateParentDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateParentDtoRole = {
  FATHER: "father",
  MOTHER: "mother",
} as const;
