/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface CreateInitUserInfoDto {
  /** 회원 이름 */
  name: string;
  /** 사업자 여부 */
  isBiz?: boolean;
}
