/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 펫인지 알인지 여부
 */
export type CreateParentDtoChildType =
  (typeof CreateParentDtoChildType)[keyof typeof CreateParentDtoChildType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateParentDtoChildType = {
  EGG: "egg",
  PET: "pet",
} as const;
