/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { CreateAdoptionDtoStatus } from "./createAdoptionDtoStatus";

export interface CreateAdoptionDto {
  /** 펫 ID */
  petId: string;
  /** 희망 분양가 */
  price?: number;
  /** 메모 */
  memo?: string;
  /** 분양 상태 */
  status?: CreateAdoptionDtoStatus;
}
