/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { CreateAnnouncementResponseDtoStatus } from "./createAnnouncementResponseDtoStatus";

export interface CreateAnnouncementResponseDto {
  /** 생성된 공지 ID */
  id: number;
  /** 발송 상태 */
  status: CreateAnnouncementResponseDtoStatus;
  /** 안내 메시지 */
  message: string;
}
