/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { CreateAdoptionDtoLocation } from "./createAdoptionDtoLocation";
import type { CreateAdoptionDtoStatus } from "./createAdoptionDtoStatus";

export interface CreateAdoptionDto {
  /** 펫 ID */
  petId: string;
  /** 분양 가격 */
  price?: number;
  /** 분양 날짜 */
  adoptionDate?: string;
  /** 입양자 ID */
  buyerId?: string;
  /** 메모 */
  memo?: string;
  /** 분양 위치 */
  location?: CreateAdoptionDtoLocation;
  /** 판매 상태 */
  status?: CreateAdoptionDtoStatus;
}
