/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { CreateMatingDtoSpecies } from "./createMatingDtoSpecies";

export interface CreateMatingDto {
  /** 아빠 펫 ID */
  fatherId?: string;
  /** 엄마 펫 ID */
  motherId?: string;
  /** 메이팅 날짜 */
  matingDate: string;
  /** 종 */
  species: CreateMatingDtoSpecies;
}
