/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { CreatePetDtoSpecies } from "./createPetDtoSpecies";
import type { CreatePetDtoSaleStatus } from "./createPetDtoSaleStatus";
import type { CreatePetDtoSex } from "./createPetDtoSex";
import type { CreateParentDto } from "./createParentDto";

export interface CreatePetDto {
  /** 펫 이름 */
  name: string;
  /** 펫 종 */
  species: CreatePetDtoSpecies;
  /** 펫 모프 */
  morphs?: string[];
  /** 펫 형질 */
  traits?: string[];
  /** 펫 출생일 */
  birthdate?: number;
  /** 펫 성장단계 */
  growth?: string;
  /** 펫 판매 상태 */
  saleStatus?: CreatePetDtoSaleStatus;
  /** 펫 공개 여부 */
  is_public?: boolean;
  /** 펫 성별(수컷, 암컷, 미구분) */
  sex?: CreatePetDtoSex;
  /** 펫 몸무게(g) */
  weight?: number;
  /** 펫 먹이 */
  foods?: string[];
  /** 펫 소개말 */
  desc?: string;
  /** 아빠 개체 정보 */
  father?: CreateParentDto;
  /** 엄마 개체 정보 */
  mother?: CreateParentDto;
}
