/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { CreateEggDtoSpecies } from "./createEggDtoSpecies";
import type { CreateParentDto } from "./createParentDto";

export interface CreateEggDto {
  /** 알 종 */
  species: CreateEggDtoSpecies;
  /** 산란일(yyyyMMdd) */
  layingDate: number;
  /** 차수(클러치) */
  clutch?: number;
  /** 알 정보 */
  desc?: string;
  /** 해당 클러치 알 개수 */
  clutchCount: number;
  /** 아빠 개체 정보 */
  father?: CreateParentDto;
  /** 엄마 개체 정보 */
  mother?: CreateParentDto;
}
