/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface CsvUploadResponseDto {
  /** 업로드된 펫 수 */
  uploadedCount: number;
  /** 실패한 행 수 */
  failedCount: number;
  /** 에러 메시지 목록 */
  errors: string[];
  /** 미리보기 데이터 */
  previewData: string[];
}
