/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { EggDetailDtoStatus } from "./eggDetailDtoStatus";

export interface EggDetailDto {
  /** 부화 온도 */
  temperature?: number;
  /** 알 상태 */
  status?: EggDetailDtoStatus;
}
