/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UserDto } from "./userDto";
import type { PetParentDto } from "./petParentDto";

export interface EggDto {
  /** 알 아이디 */
  eggId: string;
  /** 알 주인 정보 */
  owner: UserDto;
  /** 산란일(yyyyMMdd) */
  layingDate: number;
  /** 차수(클러치) */
  clutch?: number;
  /** 동배 번호(차수 내 구분 - 순서 무관) */
  clutchOrder: number;
  /** 알 이름 */
  name: string;
  /** 알 정보 */
  desc?: string;
  /** 해칭일(yyyyMMdd) */
  hatchingDate?: number;
  /** 펫 아이디 */
  petId?: string;
  /** 아빠 개체 정보 */
  father?: PetParentDto;
  /** 엄마 개체 정보 */
  mother?: PetParentDto;
}
