/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface FamilyTreeNodeDto {
  /** 펫 아이디 */
  petId: string;
  /**
   * 아버지 펫 아이디
   * @nullable
   */
  fatherId: string | null;
  /**
   * 어머니 펫 아이디
   * @nullable
   */
  motherId: string | null;
  /**
   * 중심 개체로부터의 세대 깊이 (0=루트, null=공동 부모)
   * @nullable
   */
  depth: number | null;
  /** 펫 이름 */
  name?: string;
  /** 성별 */
  sex?: string;
  /** 모프 목록 */
  morphs?: string[];
  /** 형질 목록 */
  traits?: string[];
  /** 종 */
  species: string;
  /** 출생일 */
  hatchingDate?: string;
  /** 타입 (PET) */
  type: string;
  /** 공개 여부 */
  isPublic: boolean;
  /** 현재 유저의 소유 여부 */
  isOwner: boolean;
  /** 소유자 이름 */
  ownerName?: string;
}
