/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 중심 개체로부터의 세대 깊이 (0=루트, null=공동 부모)
 * @nullable
 */
export type FamilyTreeNodeDtoDepth = { [key: string]: unknown } | null;
