/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 아버지 펫 아이디
 * @nullable
 */
export type FamilyTreeNodeDtoFatherId = { [key: string]: unknown } | null;
