/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface FeedingDto {
  /** 피딩 ID */
  id: number;
  /** 펫 ID */
  petId: string;
  /** 피딩 날짜 */
  feedingAt: string;
  /** 피딩한 음식 목록 */
  foods?: string[];
  /** 급여량 */
  amount?: number;
  /** 메모 */
  memo?: string;
}
