/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { FeedingDto } from "./feedingDto";
import type { PageMetaDto } from "./pageMetaDto";

export type FeedingControllerGetList200 = {
  data: FeedingDto[];
  meta: PageMetaDto;
};
