/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { FeedingControllerGetListOrder } from "./feedingControllerGetListOrder";

export type FeedingControllerGetListParams = {
  /**
   * 정렬 순서
   */
  order?: FeedingControllerGetListOrder;
  /**
   * 페이지 번호
   */
  page?: number;
  /**
   * 페이지당 항목 수
   */
  itemPerPage?: number;
  /**
   * 펫 ID
   */
  petId: string;
  /**
   * 조회 시작일 (yyyy-MM-dd)
   */
  startDate?: string;
  /**
   * 조회 종료일 (yyyy-MM-dd)
   */
  endDate?: string;
};
