/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { FilterPetListResponseDtoData } from "./filterPetListResponseDtoData";

export interface FilterPetListResponseDto {
  /** 성공 여부 */
  success: boolean;
  /** 메시지 */
  message: string;
  /** 날짜 범위별 해칭 펫 목록 */
  data: FilterPetListResponseDtoData;
}
