/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetDto } from "./petDto";

/**
 * 날짜 범위별 해칭 펫 목록
 */
export type FilterPetListResponseDtoData = { [key: string]: PetDto[] };
