/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetImageItem } from "./petImageItem";

/**
 * 펫 대표 이미지 (없는 경우 null)
 * @nullable
 */
export type FindThumbnailResponseDtoData = PetImageItem | null;
