/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { FindPetParentsResponseDtoData } from "./findPetParentsResponseDtoData";

export interface FindPetParentsResponseDto {
  /** 성공 여부 */
  success: boolean;
  /** 메시지 */
  message: string;
  /** 펫 부모 정보 */
  data: FindPetParentsResponseDtoData;
}
