/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { FindPetParentsResponseDtoDataFather } from "./findPetParentsResponseDtoDataFather";
import type { FindPetParentsResponseDtoDataMother } from "./findPetParentsResponseDtoDataMother";

/**
 * 펫 부모 정보
 */
export type FindPetParentsResponseDtoData = {
  /** 아빠 개체 정보 */
  father?: FindPetParentsResponseDtoDataFather;
  /** 엄마 개체 정보 */
  mother?: FindPetParentsResponseDtoDataMother;
};
