/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { FindThumbnailResponseDtoData } from "./findThumbnailResponseDtoData";

export interface FindThumbnailResponseDto {
  /** 성공 여부 */
  success: boolean;
  /** 메시지 */
  message: string;
  /**
   * 펫 대표 이미지 (없는 경우 null)
   * @nullable
   */
  data: FindThumbnailResponseDtoData;
}
