/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { ChildPetDetailDto } from "./childPetDetailDto";
import type { PetHiddenStatusDto } from "./petHiddenStatusDto";

export type GetChildrenWithDetailsDataDtoChildrenItem = ChildPetDetailDto | PetHiddenStatusDto;
