/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { GetChildrenWithDetailsDataDtoChildrenItem } from "./getChildrenWithDetailsDataDtoChildrenItem";

export interface GetChildrenWithDetailsDataDto {
  /** 자식 펫 목록 (비공개인 경우 hiddenStatus만 포함) */
  children: GetChildrenWithDetailsDataDtoChildrenItem[];
}
