/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { GetFamilyTreeResponseDtoNodesItem } from "./getFamilyTreeResponseDtoNodesItem";

export interface GetFamilyTreeResponseDto {
  /** 가계도 노드 목록 (비공개 개체는 hiddenStatus만 포함) */
  nodes: GetFamilyTreeResponseDtoNodesItem[];
  /** 중심 개체의 pairs 테이블 기준 파트너 ID 목록 (자식 없는 페어 포함) */
  centerPairPartnerIds: string[];
}
