/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { GetParentsByPetIdResponseDtoDataFather } from "./getParentsByPetIdResponseDtoDataFather";
import type { GetParentsByPetIdResponseDtoDataMother } from "./getParentsByPetIdResponseDtoDataMother";

/**
 * 펫 부모 정보
 */
export type GetParentsByPetIdResponseDtoData = {
  /** 아빠 개체 정보 */
  father?: GetParentsByPetIdResponseDtoDataFather;
  /** 엄마 개체 정보 */
  mother?: GetParentsByPetIdResponseDtoDataMother;
};
