/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { GetSiblingsWithDetailsDataDtoSiblingsItem } from "./getSiblingsWithDetailsDataDtoSiblingsItem";

export interface GetSiblingsWithDetailsDataDto {
  /** 형제 펫 목록 (비공개인 경우 hiddenStatus만 포함) */
  siblings: GetSiblingsWithDetailsDataDtoSiblingsItem[];
}
