/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { GetSiblingsPageResponseDtoDataItem } from "./getSiblingsPageResponseDtoDataItem";
import type { PageMetaDto } from "./pageMetaDto";

export interface GetSiblingsPageResponseDto {
  /** 형제 펫 목록 (비공개인 경우 hiddenStatus만 포함) */
  data: GetSiblingsPageResponseDtoDataItem[];
  /** 페이지 메타 정보 */
  meta: PageMetaDto;
}
