/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface HiddenParentDto {
  /** 숨김 여부 */
  isHidden: boolean;
}
