/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 문의 상태
 */
export type InquiryDtoStatus = (typeof InquiryDtoStatus)[keyof typeof InquiryDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InquiryDtoStatus = {
  pending: "pending",
  answered: "answered",
} as const;
