/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { InquiryDtoStatus } from "./inquiryDtoStatus";

export interface InquiryDto {
  /** 문의 ID */
  id: number;
  /** 문의 내용 */
  content: string;
  /** 문의 상태 */
  status: InquiryDtoStatus;
  /**
   * 관리자 답변
   * @nullable
   */
  answer: string | null;
  /**
   * 답변 시각
   * @nullable
   */
  answeredAt: string | null;
  /** 문의 작성 시각 */
  createdAt: string;
}
