/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 답변 시각
 * @nullable
 */
export type InquiryDtoAnsweredAt = { [key: string]: unknown } | null;
