/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface KakaoNativeLoginRequestDto {
  /** 카카오 계정 이메일 */
  email: string;
  /** 카카오 사용자 ID */
  id: string;
  /** 카카오 Refresh Token */
  refreshToken?: string;
}
