/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface LayingDto {
  /** 알 아이디 */
  eggId: string;
  /** 차수(클러치) */
  clutch?: number;
  /** 동배 번호(차수 내 구분 - 순서 무관) */
  clutchOrder: number;
  /** 알 보관 온도 */
  temperature?: number;
  /** 해칭된 펫 아이디 */
  hatchedPetId?: string;
}
