/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetLayingDto } from "./petLayingDto";

export interface LayingWithPetsDto {
  /** 차수(클러치) */
  clutch?: number;
  /** 산란 ID */
  layingId: number;
  /** 산란 날짜 */
  layingDate?: string;
  /** 펫 정보 */
  pets?: PetLayingDto[];
}
