/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetSummaryLayingDto } from "./petSummaryLayingDto";

export interface LayingByDateDto {
  /** 산란 ID */
  layingId: number;
  /** 산란 날짜 */
  layingDate: string;
  /** 산란 정보 */
  layings: PetSummaryLayingDto[];
}
