/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { LayingByDateDto } from "./layingByDateDto";

export interface MatingByDateDto {
  /** 메이팅 ID */
  id: number;
  /** 메이팅 날짜 */
  matingDate?: string;
  /** 산란 정보 */
  layingsByDate?: LayingByDateDto[];
}
