/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface MatingBaseDto {
  /** Mating ID */
  matingId: number;
  /** User ID */
  userId: string;
  /** Father ID */
  fatherId?: string;
  /** Mother ID */
  motherId?: string;
  /** Mating Date */
  matingDate: number;
  /** 생성일 */
  createdAt: string;
  /** 수정일 */
  updatedAt: string;
}
