/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { MatingByParentsDto } from "./matingByParentsDto";

export interface MatingDetailResponseDto {
  /** 성공 여부 */
  success: boolean;
  /** 메시지 */
  message: string;
  /** 메이팅 정보 */
  data: MatingByParentsDto[];
}
