/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { LayingWithPetsDto } from "./layingWithPetsDto";

export interface MatingWithLayingsDto {
  /** 메이팅 ID */
  matingId: number;
  /** 메이팅 날짜 */
  matingDate?: string;
  /** 메이팅 시즌 (몇 차) */
  season?: number;
  /** 산란 정보 */
  layings?: LayingWithPetsDto[];
}
