/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { MyAuctionItemDtoStatus } from "./myAuctionItemDtoStatus";

export interface MyAuctionItemDto {
  auctionId: string;
  shareToken: string;
  petId: string;
  status: MyAuctionItemDtoStatus;
  startTimeMs: number;
  currentEndTimeMs: number;
  startingPrice: number;
  /** @nullable */
  highestBid: number | null;
  /** @nullable */
  finalPrice: number | null;
}
