/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { NativeLoginResponseDtoRole } from "./nativeLoginResponseDtoRole";
import type { NativeLoginResponseDtoStatus } from "./nativeLoginResponseDtoStatus";

export interface NativeLoginResponseDto {
  /** 회원 고유 ID */
  userId: string;
  /** 회원 이름 */
  name: string;
  /** 회원 이메일 */
  email: string;
  /** 회원 역할 */
  role: NativeLoginResponseDtoRole;
  /** 사업자 여부 */
  isBiz: boolean;
  /**
   * refresh token
   * @nullable
   */
  refreshToken: string | null;
  /**
   * refresh token 만료 시간
   * @nullable
   */
  refreshTokenExpiresAt: string | null;
  /** 유저 상태 */
  status: NativeLoginResponseDtoStatus;
  /** 생성 시간 */
  createdAt: string;
  /** 수정 시간 */
  updatedAt: string;
  /** Access Token */
  accessToken: string;
}
