/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * refresh token 만료 시간
 */
export type NativeLoginResponseDtoRefreshTokenExpiresAt = { [key: string]: unknown };
