/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface NotificationSellerDto {
  /** 판매자 ID */
  id: string;
  /** 판매자 이름 */
  name?: string;
}
