/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { NotificationAdoptionPetDtoThumbnailUrl } from "./notificationAdoptionPetDtoThumbnailUrl";

export interface NotificationAdoptionPetDto {
  /** 개체 아이디 */
  id: string;
  /** 개체 이름 */
  name?: string;
  /**
   * 펫 썸네일 이미지 URL
   * @nullable
   */
  thumbnailUrl?: NotificationAdoptionPetDtoThumbnailUrl;
}
