/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 펫 썸네일 이미지 URL
 * @nullable
 */
export type NotificationAdoptionPetDtoThumbnailUrl = { [key: string]: unknown } | null;
