/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PageDtoDataItem } from "./pageDtoDataItem";
import type { PageMetaDto } from "./pageMetaDto";

export interface PageDto {
  /** 페이징된 데이터 */
  data: PageDtoDataItem[];
  /** 페이지 메타 정보 */
  meta: PageMetaDto;
}
