/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface PageMetaDto {
  /** 페이지 번호 */
  page: number;
  /** 페이지당 항목 수 */
  itemPerPage: number;
  /** 총 항목 수 */
  totalCount: number;
  /** 총 페이지 수 */
  totalPage: number;
  /** 이전 페이지 존재 여부 */
  hasPreviousPage: boolean;
  /** 다음 페이지 존재 여부 */
  hasNextPage: boolean;
}
