/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { EggStatisticsDto } from "./eggStatisticsDto";
import type { DistributionItemDto } from "./distributionItemDto";

export interface PairSummaryDto {
  /** 총 메이팅 횟수 */
  totalMatings: number;
  /** 총 산란 횟수 */
  totalLayings: number;
  /** 알 통계 */
  egg: EggStatisticsDto;
  /** 모프 분포 */
  morphs: DistributionItemDto[];
}
