/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type PairControllerGetPairListEggStatus =
  (typeof PairControllerGetPairListEggStatus)[keyof typeof PairControllerGetPairListEggStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PairControllerGetPairListEggStatus = {
  UNFERTILIZED: "UNFERTILIZED",
  FERTILIZED: "FERTILIZED",
  HATCHED: "HATCHED",
  DEAD: "DEAD",
} as const;
