/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PairDtoSpecies } from "./pairDtoSpecies";
import type { PairParentDto } from "./pairParentDto";

export interface PairDto {
  /** 페어 ID */
  id: number;
  /** 펫 종 */
  species: PairDtoSpecies;
  /** 아빠 펫 정보 */
  father?: PairParentDto;
  /** 엄마 펫 정보 */
  mother?: PairParentDto;
}
