/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { MatingWithLayingsDto } from "./matingWithLayingsDto";

export interface PairDetailDto {
  /** 페어 ID */
  pairId: number;
  /** 아빠 펫 ID */
  fatherId: string;
  /** 엄마 펫 ID */
  motherId: string;
  /** 메이팅 정보 */
  matings?: MatingWithLayingsDto[];
}
