/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PairParentDtoGrowth } from "./pairParentDtoGrowth";
import type { PairParentDtoSex } from "./pairParentDtoSex";
import type { PetImageItem } from "./petImageItem";

export interface PairParentDto {
  /** 펫 아이디 */
  petId: string;
  /** 펫 이름 */
  name?: string;
  /** 펫 성장단계 */
  growth?: PairParentDtoGrowth;
  /** 펫 성별(수컷, 암컷, 미구분) */
  sex?: PairParentDtoSex;
  /** 펫 모프 */
  morphs?: string[];
  /** 펫 형질 */
  traits?: string[];
  /** 펫 몸무게(g) */
  weight?: number;
  /** 펫 대표 이미지 */
  thumbnail?: PetImageItem;
}
