/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetSummaryDto } from "./petSummaryDto";

export interface ParentWithChildrenDto {
  /** 부모 펫 정보 */
  parent: PetSummaryDto;
  /** 자식 펫 목록 */
  children: PetSummaryDto[];
  /** 자식 펫 수 */
  childrenCount: number;
}
