/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 부모 관계 상태
      - pending: 승인 대기 중
      - approved: 부모 승인됨
      - rejected: 수신자에 의해 요청 거절됨
      - deleted: approved 이후, 부모 정보 변경을 위해 삭제
      - cancelled: 승인 전, 전송자의 요청 취소
 */
export type ParentDtoStatus = (typeof ParentDtoStatus)[keyof typeof ParentDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParentDtoStatus = {
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
  deleted: "deleted",
  cancelled: "cancelled",
} as const;
