/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type ParentControllerFindParentParams = {
  /**
   * 부모 구분
   */
  role: string;
};
