/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetAdoptionDtoStatus } from "./petAdoptionDtoStatus";
import type { UserProfilePublicDto } from "./userProfilePublicDto";

export interface PetAdoptionDto {
  /** 분양 가격 */
  price: number;
  /** 분양 상태 */
  status: PetAdoptionDtoStatus;
  /** 메모 */
  memo: string;
  /** 분양 구매자 */
  buyer?: UserProfilePublicDto;
  /** 분양 펫 아이디 */
  petId: string;
}
