/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetAdoptionDtoStatus } from "./petAdoptionDtoStatus";
import type { PetAdoptionDtoLocation } from "./petAdoptionDtoLocation";

export interface PetAdoptionDto {
  /** 분양 아이디 */
  adoptionId: string;
  /** 분양 가격 */
  price: number;
  /** 분양 상태 */
  status: PetAdoptionDtoStatus;
  /** 분양 날짜 */
  adoptionDate: string;
  /** 메모 */
  memo: string;
  /** 분양 위치 */
  location?: PetAdoptionDtoLocation;
  /** 분양 구매자 아이디 */
  buyerId: string;
  /** 분양 펫 아이디 */
  petId: string;
}
