/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 분양 상태
 */
export type PetAdoptionDtoStatus = (typeof PetAdoptionDtoStatus)[keyof typeof PetAdoptionDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetAdoptionDtoStatus = {
  NFS: "NFS",
  ON_SALE: "ON_SALE",
  ON_RESERVATION: "ON_RESERVATION",
} as const;
