/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { AdoptionHistoryDto } from "./adoptionHistoryDto";
import type { PageMetaDto } from "./pageMetaDto";

export type PetAdoptionControllerGetAllAdoptions200 = {
  data: AdoptionHistoryDto[];
  meta: PageMetaDto;
};
