/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type PetControllerGetParentsByPetIdStatusesItem =
  (typeof PetControllerGetParentsByPetIdStatusesItem)[keyof typeof PetControllerGetParentsByPetIdStatusesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetControllerGetParentsByPetIdStatusesItem = {
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
  deleted: "deleted",
  cancelled: "cancelled",
} as const;
