/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { SiblingPetDetailDto } from "./siblingPetDetailDto";
import type { PetHiddenStatusDto } from "./petHiddenStatusDto";

export type PetControllerGetClutchMatesByPetId200DataItem =
  | SiblingPetDetailDto
  | PetHiddenStatusDto;
