/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetControllerGetClutchMatesByPetIdType } from "./petControllerGetClutchMatesByPetIdType";

export type PetControllerGetClutchMatesByPetIdParams = {
  /**
   * 펫 타입 필터 (EGG, PET)
   */
  type?: PetControllerGetClutchMatesByPetIdType;
};
