/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetDto } from "./petDto";

export type PetControllerPreviewCsv200Data = {
  uploadedCount?: number;
  failedCount?: number;
  errors?: string[];
  previewData?: PetDto[];
};
