/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetControllerGetSiblingsByPetIdOrder } from "./petControllerGetSiblingsByPetIdOrder";
import type { PetControllerGetSiblingsByPetIdType } from "./petControllerGetSiblingsByPetIdType";

export type PetControllerGetSiblingsByPetIdParams = {
  /**
   * 정렬 순서
   */
  order?: PetControllerGetSiblingsByPetIdOrder;
  /**
   * 페이지 번호
   */
  page?: number;
  /**
   * 페이지당 항목 수
   */
  itemPerPage?: number;
  /**
   * 펫 타입 필터 (EGG, PET)
   */
  type?: PetControllerGetSiblingsByPetIdType;
};
