/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetControllerGetClutchMatesByPetId200DataItem } from "./petControllerGetClutchMatesByPetId200DataItem";

export type PetControllerGetClutchMatesByPetId200 = {
  data: PetControllerGetClutchMatesByPetId200DataItem[];
};
