/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetSummaryDto } from "./petSummaryDto";
import type { PageMetaDto } from "./pageMetaDto";

export type PetControllerFindAll200 = {
  data: PetSummaryDto[];
  meta: PageMetaDto;
};
