/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { BulkCreatePetResultDto } from "./bulkCreatePetResultDto";

export type PetControllerBulkCreate200 = {
  success: boolean;
  message: string;
  data: BulkCreatePetResultDto;
};
