/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type PetControllerFindAllSortBy =
  (typeof PetControllerFindAllSortBy)[keyof typeof PetControllerFindAllSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetControllerFindAllSortBy = {
  createdAt: "createdAt",
  hatchingDate: "hatchingDate",
} as const;
