/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type PetControllerGetClutchMatesByPetIdType =
  (typeof PetControllerGetClutchMatesByPetIdType)[keyof typeof PetControllerGetClutchMatesByPetIdType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetControllerGetClutchMatesByPetIdType = {
  EGG: "EGG",
  PET: "PET",
} as const;
