/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type PetControllerGetFamilyTreeParams = {
  /**
   * 최대 탐색 깊이 (기본값 5, 최대 7)
   */
  depth?: number;
  /**
   * 조상(부모·조부모 등) 탐색 깊이 (기본값 2, 최대 5)
   */
  ancestorDepth?: number;
};
