/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetControllerPreviewCsv200Data } from "./petControllerPreviewCsv200Data";

export type PetControllerPreviewCsv200 = {
  success?: boolean;
  message?: string;
  data?: PetControllerPreviewCsv200Data;
};
