/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type PetControllerGetChildrenByPetIdOrder =
  (typeof PetControllerGetChildrenByPetIdOrder)[keyof typeof PetControllerGetChildrenByPetIdOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetControllerGetChildrenByPetIdOrder = {
  ASC: "ASC",
  DESC: "DESC",
} as const;
