/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetControllerUploadCsv200Data } from "./petControllerUploadCsv200Data";

export type PetControllerUploadCsv200 = {
  success?: boolean;
  message?: string;
  data?: PetControllerUploadCsv200Data;
};
