/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetControllerGetParentsByPetIdStatusesItem } from "./petControllerGetParentsByPetIdStatusesItem";

export type PetControllerGetParentsByPetIdParams = {
  /**
   * 부모 요청 상태 필터 (기본: PENDING, APPROVED)
   */
  statuses?: PetControllerGetParentsByPetIdStatusesItem[];
};
