/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type PetControllerFeedParams = {
  /**
   * 셔플 시드 (클라이언트 타임스탬프)
   */
  seed: number;
  /**
   * 페이지 번호
   */
  page?: number;
  /**
   * 페이지당 항목 수
   */
  itemPerPage?: number;
  /**
   * 셔플 배열 시작 오프셋 (pull-to-refresh 시 랜덤 값으로 다른 위치부터 순환 조회)
   */
  startOffset?: number;
};
