/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetDtoType } from "./petDtoType";
import type { UserProfilePublicDto } from "./userProfilePublicDto";
import type { PetDtoSpecies } from "./petDtoSpecies";
import type { PetDetailDto } from "./petDetailDto";
import type { EggDetailDto } from "./eggDetailDto";
import type { PetParentDto } from "./petParentDto";
import type { PetAdoptionDto } from "./petAdoptionDto";
import type { PetDtoStatus } from "./petDtoStatus";
import type { PetImageItem } from "./petImageItem";

export interface PetDto {
  /** 펫 아이디 */
  petId: string;
  /** 펫 타입(egg/pet) */
  type?: PetDtoType;
  /** 펫 주인 정보 */
  owner: UserProfilePublicDto;
  /** 펫 이름 */
  name?: string;
  /** 펫 종 */
  species: PetDtoSpecies;
  /** 펫 출생일 */
  hatchingDate?: string;
  /** 펫 공개 여부 */
  isPublic?: boolean;
  /** 펫 이미지 목록 */
  photoOrder?: string[];
  /** 펫 소개말 */
  desc?: string;
  /** 펫 상세 정보 */
  petDetail?: PetDetailDto;
  /** 알 상세 정보 */
  eggDetail?: EggDetailDto;
  /** 아빠 개체 정보 */
  father?: PetParentDto;
  /** 엄마 개체 정보 */
  mother?: PetParentDto;
  /** 분양 정보 */
  adoption?: PetAdoptionDto;
  /** 부모 관계 상태 */
  status: PetDtoStatus;
  /** 펫 이미지 목록 */
  photos?: PetImageItem[];
}
