/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetDetailSummaryDtoSex } from "./petDetailSummaryDtoSex";

export interface PetDetailSummaryDto {
  /** 펫 성별(수컷, 암컷, 미구분) */
  sex?: PetDetailSummaryDtoSex;
  /** 펫 모프 */
  morphs?: string[];
  /** 펫 형질 */
  traits?: string[];
}
