/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 펫 성별(수컷, 암컷, 미구분)
 */
export type PetDetailBaseDtoSex = (typeof PetDetailBaseDtoSex)[keyof typeof PetDetailBaseDtoSex];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetDetailBaseDtoSex = {
  MALE: "M",
  FEMALE: "F",
  NON: "N",
} as const;
