/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 알 상태
 */
export type PetDtoEggStatus = (typeof PetDtoEggStatus)[keyof typeof PetDtoEggStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetDtoEggStatus = {
  UNFERTILIZED: "UNFERTILIZED",
  FERTILIZED: "FERTILIZED",
  HATCHED: "HATCHED",
  DEAD: "DEAD",
} as const;
