/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetDetailBaseDtoGrowth } from "./petDetailBaseDtoGrowth";
import type { PetDetailBaseDtoSex } from "./petDetailBaseDtoSex";

export interface PetDetailBaseDto {
  /** 펫 성장단계 */
  growth?: PetDetailBaseDtoGrowth;
  /** 펫 성별(수컷, 암컷, 미구분) */
  sex?: PetDetailBaseDtoSex;
  /** 펫 모프 */
  morphs?: string[];
  /** 펫 형질 */
  traits?: string[];
  /** 펫 먹이 */
  foods?: string[];
  /** 펫 몸무게(g) */
  weight?: number;
}
