/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UserProfilePublicDto } from "./userProfilePublicDto";
import type { PetDtoSpecies } from "./petDtoSpecies";
import type { PetDtoGrowth } from "./petDtoGrowth";
import type { PetDtoSex } from "./petDtoSex";
import type { PetParentDto } from "./petParentDto";
import type { PetAdoptionDto } from "./petAdoptionDto";
import type { PetDtoStatus } from "./petDtoStatus";

export interface PetDto {
  /** 펫 아이디 */
  petId: string;
  /** 펫 주인 정보 */
  owner: UserProfilePublicDto;
  /** 펫 이름 */
  name?: string;
  /** 펫 종 */
  species: PetDtoSpecies;
  /** 펫 모프 */
  morphs?: string[];
  /** 펫 형질 */
  traits?: string[];
  /** 펫 출생일 */
  hatchingDate?: string;
  /** 펫 성장단계 */
  growth?: PetDtoGrowth;
  /** 펫 공개 여부 */
  isPublic?: boolean;
  /** 펫 성별(수컷, 암컷, 미구분) */
  sex?: PetDtoSex;
  /** 펫 몸무게(g) */
  weight?: number;
  /** 펫 먹이 */
  foods?: string[];
  /** 펫 이미지 목록 */
  photos?: string[];
  /** 펫 소개말 */
  desc?: string;
  /** 아빠 개체 정보 */
  father?: PetParentDto;
  /** 엄마 개체 정보 */
  mother?: PetParentDto;
  /** 분양 정보 */
  adoption?: PetAdoptionDto;
  /** 부모 관계 상태 */
  status: PetDtoStatus;
}
