/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetDtoSpecies } from "./petDtoSpecies";
import type { PetDtoSex } from "./petDtoSex";

export interface PetDto {
  /** 펫 아이디 */
  petId: string;
  /** 펫 주인 아이디 */
  ownerId: string;
  /** 펫 이름 */
  name: string;
  /** 펫 종 */
  species: PetDtoSpecies;
  /** 펫 모프 */
  morphs?: string[];
  /** 펫 형질 */
  traits?: string[];
  /** 펫 출생일 */
  birthdate?: string;
  /** 펫 성장단계 */
  growth?: string;
  /** 펫 성별(수컷, 암컷, 미구분) */
  sex?: PetDtoSex;
  /** 펫 몸무게(g) */
  weight?: number;
  /** 펫 먹이 */
  foods?: string[];
  /** 펫 소개말 */
  desc?: string;
}
