/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 펫 성별(수컷, 암컷, 미구분)
 */
export type PetDtoSex = { [key: string]: unknown };
