/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 펫 성장단계
 */
export type PetDtoGrowth = (typeof PetDtoGrowth)[keyof typeof PetDtoGrowth];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetDtoGrowth = {
  BABY: "BABY",
  JUVENILE: "JUVENILE",
  PRE_ADULT: "PRE_ADULT",
  ADULT: "ADULT",
  DEAD: "DEAD",
} as const;
