/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetFamilyPairGroupDto } from "./petFamilyPairGroupDto";

/**
 * pairId별로 그룹화된 펫 데이터
 */
export type PetFamilyTreeResponseDtoPairData = { [key: string]: PetFamilyPairGroupDto };
