/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetFullDtoType } from "./petFullDtoType";
import type { UserProfilePublicDto } from "./userProfilePublicDto";
import type { PetFullDtoSpecies } from "./petFullDtoSpecies";
import type { PetDetailBaseDto } from "./petDetailBaseDto";
import type { EggDetailDto } from "./eggDetailDto";
import type { LayingDto } from "./layingDto";
import type { PetFullDtoGrowth } from "./petFullDtoGrowth";
import type { PetFullDtoSex } from "./petFullDtoSex";
import type { PetFullDtoEggStatus } from "./petFullDtoEggStatus";
import type { PetFullDtoFather } from "./petFullDtoFather";
import type { PetFullDtoMother } from "./petFullDtoMother";
import type { PetFullDtoStatus } from "./petFullDtoStatus";
import type { PetImageItem } from "./petImageItem";

export interface PetFullDto {
  /** 펫 아이디 */
  petId: string;
  /** 펫 타입(egg/pet) */
  type?: PetFullDtoType;
  /** 펫 주인 정보 */
  owner: UserProfilePublicDto;
  /** 펫 이름 */
  name?: string;
  /** 펫 종 */
  species: PetFullDtoSpecies;
  /** 펫 출생일 */
  hatchingDate?: string;
  /** 펫 이미지 목록 */
  photoOrder?: string[];
  /** 펫 소개말 */
  desc?: string;
  /** 펫 공개 여부 */
  isPublic?: boolean;
  /** 펫 삭제 여부 */
  isDeleted?: boolean;
  /** 펫 상세 정보 */
  petDetail?: PetDetailBaseDto;
  /** 알 상세 정보 */
  eggDetail?: EggDetailDto;
  /** 산란 정보 */
  laying?: LayingDto;
  /** 펫 성장단계 */
  growth?: PetFullDtoGrowth;
  /** 펫 성별(수컷, 암컷, 미구분) */
  sex?: PetFullDtoSex;
  /** 펫 모프 */
  morphs?: string[];
  /** 펫 형질 */
  traits?: string[];
  /** 펫 먹이 */
  foods?: string[];
  /** 펫 몸무게(g) */
  weight?: number;
  /** 부화 온도 */
  temperature?: number;
  /** 알 상태 */
  eggStatus?: PetFullDtoEggStatus;
  /** 아빠 개체 정보 */
  father?: PetFullDtoFather;
  /** 엄마 개체 정보 */
  mother?: PetFullDtoMother;
  /** 부모 관계 상태 */
  status: PetFullDtoStatus;
  /** 펫 이미지 목록 */
  photos?: PetImageItem[];
}
