/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetFamilyTreeResponseDtoPairData } from "./petFamilyTreeResponseDtoPairData";

export interface PetFamilyTreeResponseDto {
  /** pairId별로 그룹화된 펫 데이터 */
  pairData: PetFamilyTreeResponseDtoPairData;
}
