/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetHiddenStatusDtoHiddenStatus } from "./petHiddenStatusDtoHiddenStatus";

export interface PetHiddenStatusDto {
  /** 숨김 처리된 원인 */
  hiddenStatus: PetHiddenStatusDtoHiddenStatus;
}
