/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 숨김 처리된 원인
 */
export type PetHiddenStatusDtoHiddenStatus =
  (typeof PetHiddenStatusDtoHiddenStatus)[keyof typeof PetHiddenStatusDtoHiddenStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetHiddenStatusDtoHiddenStatus = {
  SECRET: "SECRET",
  PENDING: "PENDING",
  DELETED: "DELETED",
} as const;
