/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface PetImageBaseDto {
  /** 펫 이미지 아이디 */
  id: number;
  /** 펫 이미지 파일 */
  fileName: string;
  /** 펫 이미지 원본 url */
  url: string;
  /** 펫 이미지 파일 타입 */
  mimeType: string;
  /** 펫 이미지 파일 크기 */
  size: number;
  createdAt: string;
  updatedAt: string;
}
