/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UserProfilePublicDto } from "./userProfilePublicDto";
import type { PetParentDtoSpecies } from "./petParentDtoSpecies";
import type { PetParentDtoStatus } from "./petParentDtoStatus";
import type { PetParentDtoSex } from "./petParentDtoSex";
import type { PetImageItem } from "./petImageItem";

export interface PetParentDto {
  /** 펫 아이디 */
  petId: string;
  /** 펫 주인 정보 */
  owner: UserProfilePublicDto;
  /** 펫 이름 */
  name?: string;
  /** 펫 종 */
  species: PetParentDtoSpecies;
  /** 펫 출생일 */
  hatchingDate?: string;
  /** 펫 공개 여부 */
  isPublic?: boolean;
  /** 펫 삭제 여부 */
  isDeleted?: boolean;
  /** 부모 관계 상태 */
  status: PetParentDtoStatus;
  /** 펫 성별(수컷, 암컷, 미구분) */
  sex?: PetParentDtoSex;
  /** 펫 모프 */
  morphs?: string[];
  /** 펫 형질 */
  traits?: string[];
  /** 펫 이미지 목록 */
  photos?: PetImageItem[];
  /** 숨김 여부 */
  isHidden?: boolean;
}
