/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 펫 타입(egg/pet)
 */
export type PetSummaryWithoutOwnerDtoType =
  (typeof PetSummaryWithoutOwnerDtoType)[keyof typeof PetSummaryWithoutOwnerDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetSummaryWithoutOwnerDtoType = {
  EGG: "EGG",
  PET: "PET",
} as const;
