/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetSummaryWithoutOwnerDtoSpecies } from "./petSummaryWithoutOwnerDtoSpecies";
import type { PetSummaryWithoutOwnerDtoSex } from "./petSummaryWithoutOwnerDtoSex";

export interface PetSummaryWithoutOwnerDto {
  /** 펫 아이디 */
  petId: string;
  /** 펫 이름 */
  name?: string;
  /** 펫 종 */
  species: PetSummaryWithoutOwnerDtoSpecies;
  /** 펫 모프 */
  morphs?: string[];
  /** 펫 형질 */
  traits?: string[];
  /** 펫 출생일 */
  hatchingDate?: string;
  /** 펫 성별(수컷, 암컷, 미구분) */
  sex?: PetSummaryWithoutOwnerDtoSex;
  /** 펫 이미지 목록 */
  photos?: string[];
}
