/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetSingleDtoType } from "./petSingleDtoType";
import type { UserProfilePublicDto } from "./userProfilePublicDto";
import type { PetSingleDtoSpecies } from "./petSingleDtoSpecies";
import type { PetDetailBaseDto } from "./petDetailBaseDto";
import type { EggDetailDto } from "./eggDetailDto";
import type { LayingDto } from "./layingDto";
import type { PetSingleDtoGrowth } from "./petSingleDtoGrowth";
import type { PetSingleDtoSex } from "./petSingleDtoSex";
import type { PetSingleDtoEggStatus } from "./petSingleDtoEggStatus";
import type { PetSingleDtoFather } from "./petSingleDtoFather";
import type { PetSingleDtoMother } from "./petSingleDtoMother";
import type { PetSingleDtoStatus } from "./petSingleDtoStatus";
import type { PetImageItem } from "./petImageItem";

export interface PetSingleDto {
  /** 펫 아이디 */
  petId: string;
  /** 펫 타입(egg/pet) */
  type?: PetSingleDtoType;
  /** 펫 주인 정보 */
  owner: UserProfilePublicDto;
  /** 펫 이름 */
  name?: string;
  /** 펫 종 */
  species: PetSingleDtoSpecies;
  /** 펫 출생일 */
  hatchingDate?: string;
  /** 펫 이미지 목록 */
  photoOrder?: string[];
  /** 펫 소개말 */
  desc?: string;
  /** 펫 공개 여부 */
  isPublic?: boolean;
  /** 펫 삭제 여부 */
  isDeleted?: boolean;
  /** 펫 상세 정보 */
  petDetail?: PetDetailBaseDto;
  /** 알 상세 정보 */
  eggDetail?: EggDetailDto;
  /** 산란 정보 */
  laying?: LayingDto;
  /** 펫 성장단계 */
  growth?: PetSingleDtoGrowth;
  /** 펫 성별(수컷, 암컷, 미구분) */
  sex?: PetSingleDtoSex;
  /** 펫 모프 */
  morphs?: string[];
  /** 펫 형질 */
  traits?: string[];
  /** 펫 먹이 */
  foods?: string[];
  /** 펫 몸무게(g) */
  weight?: number;
  /** 부화 온도 */
  temperature?: number;
  /** 알 상태 */
  eggStatus?: PetSingleDtoEggStatus;
  /** 아빠 개체 정보 */
  father?: PetSingleDtoFather;
  /** 엄마 개체 정보 */
  mother?: PetSingleDtoMother;
  /** 부모 관계 상태 */
  status: PetSingleDtoStatus;
  /** 펫 이미지 목록 */
  photos?: PetImageItem[];
}
