/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetSummaryWithLayingDtoType } from "./petSummaryWithLayingDtoType";
import type { UserProfilePublicDto } from "./userProfilePublicDto";
import type { PetSummaryWithLayingDtoSpecies } from "./petSummaryWithLayingDtoSpecies";
import type { PetDetailSummaryDto } from "./petDetailSummaryDto";
import type { PetImageItem } from "./petImageItem";
import type { PetSummaryWithLayingDtoEggStatus } from "./petSummaryWithLayingDtoEggStatus";

export interface PetSummaryWithLayingDto {
  /** 펫 아이디 */
  petId: string;
  /** 펫 타입(egg/pet) */
  type?: PetSummaryWithLayingDtoType;
  /** 펫 주인 정보 */
  owner: UserProfilePublicDto;
  /** 펫 이름 */
  name?: string;
  /** 펫 종 */
  species: PetSummaryWithLayingDtoSpecies;
  /** 펫 출생일 */
  hatchingDate?: string;
  /** 펫 이미지 목록 */
  photoOrder?: string[];
  /** 펫 상세 정보 */
  petDetailSummary?: PetDetailSummaryDto;
  /** 펫 이미지 목록 */
  photos?: PetImageItem[];
  /** 산란 아이디 */
  layingId?: number;
  /** 산란 클러치 */
  clutch?: number;
  /** 산란 클러치 순서 */
  clutchOrder?: number;
  /** 펫 온도 */
  temperature?: number;
  /** 알 상태 */
  eggStatus: PetSummaryWithLayingDtoEggStatus;
}
