/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface PetSnapshotParentDto {
  /** 부/모 개체 ID */
  petId: string;
  /** 부/모 개체 이름 */
  name?: string;
}
