/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetSummaryAdoptionDtoType } from "./petSummaryAdoptionDtoType";
import type { PetSummaryAdoptionDtoSpecies } from "./petSummaryAdoptionDtoSpecies";
import type { PetSummaryAdoptionDtoSex } from "./petSummaryAdoptionDtoSex";
import type { PetSummaryAdoptionDtoGrowth } from "./petSummaryAdoptionDtoGrowth";
import type { PetImageItem } from "./petImageItem";

export interface PetSummaryAdoptionDto {
  /** 펫 아이디 */
  petId: string;
  /** 펫 타입(egg/pet) */
  type?: PetSummaryAdoptionDtoType;
  /** 펫 이름 */
  name?: string;
  /** 펫 종 */
  species: PetSummaryAdoptionDtoSpecies;
  /** 펫 출생일 */
  hatchingDate?: string;
  /** 펫 성별(수컷, 암컷, 미구분) */
  sex?: PetSummaryAdoptionDtoSex;
  /** 펫 모프 */
  morphs?: string[];
  /** 펫 형질 */
  traits?: string[];
  /** 펫 성장단계 */
  growth?: PetSummaryAdoptionDtoGrowth;
  /** 펫 이미지 목록 */
  photos?: PetImageItem[];
}
