/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 부모 관계 상태
 */
export type PetSingleDtoStatus = (typeof PetSingleDtoStatus)[keyof typeof PetSingleDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetSingleDtoStatus = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  DELETED: "deleted",
  CANCELLED: "cancelled",
} as const;
