/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 펫 상태
 */
export type PetSummaryWithLayingDtoStatus =
  (typeof PetSummaryWithLayingDtoStatus)[keyof typeof PetSummaryWithLayingDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetSummaryWithLayingDtoStatus = {
  UNFERTILIZED: "UNFERTILIZED",
  FERTILIZED: "FERTILIZED",
  HATCHED: "HATCHED",
  DEAD: "DEAD",
} as const;
