/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 플랫폼
 */
export type RegisterFcmTokenDtoPlatform =
  (typeof RegisterFcmTokenDtoPlatform)[keyof typeof RegisterFcmTokenDtoPlatform];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterFcmTokenDtoPlatform = {
  ios: "ios",
  android: "android",
} as const;
