/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { RegisterFcmTokenDtoPlatform } from "./registerFcmTokenDtoPlatform";

export interface RegisterFcmTokenDto {
  /** FCM 토큰 */
  token: string;
  /** 기기 고유 ID */
  deviceId: string;
  /** 플랫폼 */
  platform: RegisterFcmTokenDtoPlatform;
}
