/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { ParentRequestEntity } from "./parentRequestEntity";

export interface RequestByIdResponseDto {
  /** 성공 여부 */
  success: boolean;
  /** 메시지 */
  message: string;
  /** 부모 요청 정보 */
  data: ParentRequestEntity;
}
