/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 회원 역할
 */
export type SafeUserDtoRole = (typeof SafeUserDtoRole)[keyof typeof SafeUserDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SafeUserDtoRole = {
  USER: "user",
  BREEDER: "breeder",
  ADMIN: "admin",
} as const;
