/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { SafeUserDtoRole } from "./safeUserDtoRole";
import type { SafeUserDtoStatus } from "./safeUserDtoStatus";

export interface SafeUserDto {
  /** 회원 고유 ID */
  userId: string;
  /** 회원 이름 */
  name: string;
  /** 회원 이메일 */
  email: string;
  /** 회원 역할 */
  role: SafeUserDtoRole;
  /** 사업자 여부 */
  isBiz: boolean;
  /** 유저 상태 */
  status: SafeUserDtoStatus;
  /** 생성 시간 */
  createdAt: string;
  /** 수정 시간 */
  updatedAt: string;
}
