/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * FCM 에러 코드별 실패 토큰 수
 */
export type TestAnnouncementResponseDtoFailuresByCode = { [key: string]: unknown };
