/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { TestAnnouncementResponseDtoFailuresByCode } from "./testAnnouncementResponseDtoFailuresByCode";

export interface TestAnnouncementResponseDto {
  /** 발송 대상 토큰 수 */
  targetCount: number;
  /** 성공 토큰 수 */
  successCount: number;
  /** 실패 토큰 수 */
  failureCount: number;
  /** FCM 에러 코드별 실패 토큰 수 */
  failuresByCode: TestAnnouncementResponseDtoFailuresByCode;
}
