/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface TestAnnouncementResponseDto {
  /** 발송 대상 토큰 수 */
  targetCount: number;
  /** 성공 토큰 수 */
  successCount: number;
  /** 실패 토큰 수 */
  failureCount: number;
}
