/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 알림 타입
 */
export type UpdateUserNotificationDtoType =
  (typeof UpdateUserNotificationDtoType)[keyof typeof UpdateUserNotificationDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserNotificationDtoType = {
  parent_request: "parent_request",
  parent_accept: "parent_accept",
  parent_reject: "parent_reject",
  owner_transfer: "owner_transfer",
  owner_accept: "owner_accept",
  owner_reject: "owner_reject",
} as const;
