/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateMatingDto {
  /** Father ID */
  fatherId?: string;
  /** Mother ID */
  motherId?: string;
  /** Mating Date */
  matingDate: number;
}
