/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateLayingDateDto {
  /** 메이팅 ID */
  matingId: number;
  /** 기존 산란일(yyyyMMdd) */
  currentLayingDate: number;
  /** 새로운 산란일(yyyyMMdd) */
  newLayingDate: number;
}
