/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateAdoptionDtoStatus } from "./updateAdoptionDtoStatus";

export interface UpdateAdoptionDto {
  /**
   * 희망 분양가
   * @nullable
   */
  price?: number | null;
  /**
   * 예약자 ID
   * @nullable
   */
  reservedUserId?: string | null;
  /**
   * 메모
   * @nullable
   */
  memo?: string | null;
  /**
   * 분양 상태
   * @nullable
   */
  status?: UpdateAdoptionDtoStatus;
}
