/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserPrivateInfoDtoRealName } from "./updateUserPrivateInfoDtoRealName";
import type { UpdateUserPrivateInfoDtoPhone } from "./updateUserPrivateInfoDtoPhone";
import type { UpdateUserPrivateInfoDtoAddress } from "./updateUserPrivateInfoDtoAddress";

export interface UpdateUserPrivateInfoDto {
  /**
   * 본명
   * @nullable
   */
  realName?: UpdateUserPrivateInfoDtoRealName;
  /**
   * 전화번호
   * @nullable
   */
  phone?: UpdateUserPrivateInfoDtoPhone;
  /**
   * 주소
   * @nullable
   */
  address?: UpdateUserPrivateInfoDtoAddress;
}
