/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 분양 방식 (판매완료 시 사용)
 * @nullable
 */
export type UpdateAdoptionDtoMethod =
  | (typeof UpdateAdoptionDtoMethod)[keyof typeof UpdateAdoptionDtoMethod]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAdoptionDtoMethod = {
  PICKUP: "PICKUP",
  DELIVERY: "DELIVERY",
  WHOLESALE: "WHOLESALE",
  EXPORT: "EXPORT",
} as const;
