/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 판매 상태
 * @nullable
 */
export type UpdateAdoptionDtoStatus =
  | (typeof UpdateAdoptionDtoStatus)[keyof typeof UpdateAdoptionDtoStatus]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAdoptionDtoStatus = {
  NONE: "NONE",
  NFS: "NFS",
  ON_SALE: "ON_SALE",
  ON_RESERVATION: "ON_RESERVATION",
  SOLD: "SOLD",
  REFUNDED: "REFUNDED",
} as const;
