/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 펫 종
 */
export type UpdatePetDtoSpecies = (typeof UpdatePetDtoSpecies)[keyof typeof UpdatePetDtoSpecies];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePetDtoSpecies = {
  CRESTED: "CR",
  LEOPARD: "LE",
  FATTAIL: "FT",
  KNOPTAIL: "KN",
  LEACH: "LC",
  GARGO: "GG",
} as const;
