/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 부모 구분
 */
export type UpdateParentDtoTarget =
  (typeof UpdateParentDtoTarget)[keyof typeof UpdateParentDtoTarget];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateParentDtoTarget = {
  father: "father",
  mother: "mother",
} as const;
