/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 업데이트 할 부모 관계 상태
 */
export type UpdateParentDtoStatus =
  (typeof UpdateParentDtoStatus)[keyof typeof UpdateParentDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateParentDtoStatus = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  DELETED: "deleted",
  CANCELLED: "cancelled",
} as const;
