/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UpdatePetLimitOverrideDtoPetLimitOverride } from "./updatePetLimitOverrideDtoPetLimitOverride";

export interface UpdatePetLimitOverrideDto {
  /**
   * 사용자별 공개 펫 슬롯 한도 override (null = role 기본값으로 복귀)
   * @nullable
   */
  petLimitOverride: UpdatePetLimitOverrideDtoPetLimitOverride;
}
