/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateAdoptionHistoryDtoMemo } from "./updateAdoptionHistoryDtoMemo";

export interface UpdateAdoptionHistoryDto {
  /**
   * 메모
   * @nullable
   */
  memo?: UpdateAdoptionHistoryDtoMemo;
}
