/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { CreateParentDto } from "./createParentDto";

export interface UpdateEggDto {
  /** 산란일(yyyyMMdd) */
  layingDate?: number;
  /** 차수(클러치) */
  clutch?: number;
  /** 동배 번호(차수 내 구분 - 순서 무관) */
  clutchOrder?: number;
  /** 알 정보 */
  desc?: string;
  /** 아빠 개체 정보 */
  father?: CreateParentDto;
  /** 엄마 개체 정보 */
  mother?: CreateParentDto;
}
