/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserNotificationDtoStatus } from "./updateUserNotificationDtoStatus";

export interface UpdateUserNotificationDto {
  /** 알림 아이디 */
  id: number;
  /** 알림 상태 */
  status: UpdateUserNotificationDtoStatus;
}
