/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserPrivateInfoDto {
  /**
   * 본명
   * @nullable
   */
  realName?: string | null;
  /**
   * 전화번호
   * @nullable
   */
  phone?: string | null;
  /**
   * 주소
   * @nullable
   */
  address?: string | null;
  /** 본명 공개 여부 */
  isRealNamePublic?: boolean;
  /** 전화번호 공개 여부 */
  isPhonePublic?: boolean;
  /** 주소 공개 여부 */
  isAddressPublic?: boolean;
  /**
   * 배너 이미지 URL
   * @nullable
   */
  bannerImageUrl?: string | null;
  /**
   * 브리더 소개글
   * @nullable
   */
  bio?: string | null;
  /** 쇼룸 슬러그 (영소문자, 숫자, 밑줄 3~20자) */
  showroomSlug?: string;
}
