/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 알림 상태
      - unread: 읽지 않음
      - read: 읽음
      - deleted: 삭제
 */
export type UpdateUserNotificationDtoStatus =
  (typeof UpdateUserNotificationDtoStatus)[keyof typeof UpdateUserNotificationDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserNotificationDtoStatus = {
  read: "read",
  unread: "unread",
  deleted: "deleted",
} as const;
