/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 분양 위치
 */
export type UpdateAdoptionDtoLocation =
  (typeof UpdateAdoptionDtoLocation)[keyof typeof UpdateAdoptionDtoLocation];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAdoptionDtoLocation = {
  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
} as const;
