/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateParentDtoUpdateStatus } from "./updateParentDtoUpdateStatus";

export interface UpdateParentDto {
  /** 부모 ID */
  parentId: string;
  /** 변경할 상태 */
  updateStatus: UpdateParentDtoUpdateStatus;
}
