/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface UpdatePetLimitOverrideResponseDto {
  /** 성공 여부 */
  success: boolean;
  /** 응답 메시지 */
  message: string;
  /** 적용 후 유효 한도 */
  effectiveLimit: number;
  /** 한도 변경으로 인해 자동 비공개로 강등된 펫 ID 목록 */
  demotedPetIds: string[];
}
