/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateAdoptionDtoStatus } from "./updateAdoptionDtoStatus";

export interface UpdateAdoptionDto {
  /** 펫 ID */
  petId?: string;
  /** 분양 가격 */
  price?: number;
  /** 분양 날짜 */
  adoptionDate?: string;
  /** 입양자 ID */
  buyerId?: string;
  /** 메모 */
  memo?: string;
  /** 거래 장소 */
  location?: string;
  /** 분양 상태 */
  status?: UpdateAdoptionDtoStatus;
}
