/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateParentDtoTarget } from "./updateParentDtoTarget";

export interface UpdateParentDto {
  /** 부모 ID */
  parentId: string;
  /** 부모 구분 */
  target: UpdateParentDtoTarget;
}
