/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 변경할 상태
 */
export type UpdateParentDtoUpdateStatus =
  (typeof UpdateParentDtoUpdateStatus)[keyof typeof UpdateParentDtoUpdateStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateParentDtoUpdateStatus = {
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
  deleted: "deleted",
  cancelled: "cancelled",
} as const;
