/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateShowroomSlugDto {
  /** 쇼룸 슬러그 (영소문자, 숫자, 밑줄 3~20자) */
  slug: string;
}
