/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface UploadImagesRequestDto {
  /** 펫 아이디 */
  petId: string;
  /** 업로드할 이미지 파일 (jpg, jpeg, png, gif, webp, avif) */
  files: Blob[];
}
