/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 유저 상태
 */
export type UserDtoStatus = (typeof UserDtoStatus)[keyof typeof UserDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDtoStatus = {
  pending: "pending",
  active: "active",
  inactive: "inactive",
  suspended: "suspended",
  deleted: "deleted",
} as const;
