/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UserProfileDtoRole } from "./userProfileDtoRole";
import type { UserProfileDtoProviderItem } from "./userProfileDtoProviderItem";
import type { UserProfileDtoStatus } from "./userProfileDtoStatus";
import type { UserProfileDtoShowroomSlug } from "./userProfileDtoShowroomSlug";

export interface UserProfileDto {
  /** 회원 고유 ID */
  userId: string;
  /** 회원 이름 */
  name: string;
  /** 회원 이메일 */
  email: string;
  /** 회원 역할 */
  role: UserProfileDtoRole;
  /** 사업자 여부 */
  isBiz: boolean;
  /** Oauth 제공자 */
  provider: UserProfileDtoProviderItem[];
  /** 유저 상태 */
  status: UserProfileDtoStatus;
  /** 쇼룸 슬러그 */
  showroomSlug?: UserProfileDtoShowroomSlug;
  /** 생성 시간 */
  createdAt: string;
}
