/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 알림 타입
 */
export type UserNotificationDtoType =
  (typeof UserNotificationDtoType)[keyof typeof UserNotificationDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserNotificationDtoType = {
  PARENT_REQUEST: "parent_request",
  PARENT_ACCEPT: "parent_accept",
  PARENT_REJECT: "parent_reject",
  PARENT_CANCEL: "parent_cancel",
  ADOPTION_COMPLETE: "adoption_complete",
  AUCTION_STARTED: "auction_started",
  AUCTION_ENDED_HOST: "auction_ended_host",
  AUCTION_ENDED_WINNER: "auction_ended_winner",
  AUCTION_OUTBID: "auction_outbid",
} as const;
