/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UserDtoRole } from "./userDtoRole";

export interface UserDto {
  /** 회원 고유 ID */
  userId: string;
  /** 회원 이름 */
  name: string;
  /** 회원 역할 */
  role: UserDtoRole;
}
