/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UserPrivateInfoDto } from "./userPrivateInfoDto";

export interface UserPrivateInfoResponseDto {
  /** 성공 여부 */
  success: boolean;
  /** 메시지 */
  message: string;
  /** 사용자 개인정보 */
  data: UserPrivateInfoDto;
}
