/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UserPrivateInfoDtoRealName } from "./userPrivateInfoDtoRealName";
import type { UserPrivateInfoDtoPhone } from "./userPrivateInfoDtoPhone";
import type { UserPrivateInfoDtoAddress } from "./userPrivateInfoDtoAddress";

export interface UserPrivateInfoDto {
  /**
   * 본명
   * @nullable
   */
  realName?: UserPrivateInfoDtoRealName;
  /**
   * 전화번호
   * @nullable
   */
  phone?: UserPrivateInfoDtoPhone;
  /**
   * 주소
   * @nullable
   */
  address?: UserPrivateInfoDtoAddress;
}
