/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * Oauth 제공자 ID
 */
export type UserDtoProviderId = { [key: string]: unknown };
