/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UserNotificationDetailJsonStatus } from "./userNotificationDetailJsonStatus";
import type { NotificationPetDto } from "./notificationPetDto";
import type { UserNotificationDetailJsonRole } from "./userNotificationDetailJsonRole";

export interface UserNotificationDetailJson {
  /** 부모 연동 상태 */
  status?: UserNotificationDetailJsonStatus;
  /** 자식 개체 정보 */
  childPet?: NotificationPetDto;
  /** 부모 개체 정보 */
  parentPet?: NotificationPetDto;
  /** 부모 역할 */
  role?: UserNotificationDetailJsonRole;
  /** 메시지 */
  message?: string;
  /** 거절 이유 */
  rejectReason?: string;
}
