/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface UserPrivateInfoDto {
  /**
   * 본명
   * @nullable
   */
  realName?: string | null;
  /**
   * 전화번호
   * @nullable
   */
  phone?: string | null;
  /**
   * 주소
   * @nullable
   */
  address?: string | null;
}
