/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UserProfileDtoRole } from "./userProfileDtoRole";
import type { UserProfileDtoProvider } from "./userProfileDtoProvider";
import type { UserProfileDtoStatus } from "./userProfileDtoStatus";

export interface UserProfileDto {
  /** 회원 고유 ID */
  userId: string;
  /** 회원 이름 */
  name: string;
  /** 회원 역할 */
  role: UserProfileDtoRole;
  /** 사업자 여부 */
  isBiz: boolean;
  /** Oauth 제공자 */
  provider: UserProfileDtoProvider;
  /** 유저 상태 */
  status: UserProfileDtoStatus;
  /** 마지막 로그인 시간 */
  lastLoginAt: string;
  /** 생성 시간 */
  createdAt: string;
}
