/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 전화번호
 * @nullable
 */
export type UserPrivateInfoDtoPhone = { [key: string]: unknown } | null;
