/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 유저 상태
 */
export type UserProfileDtoStatus = (typeof UserProfileDtoStatus)[keyof typeof UserProfileDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserProfileDtoStatus = {
  PENDING: "pending",
  ACTIVE: "active",
  INACTIVE: "inactive",
  SUSPENDED: "suspended",
  DELETED: "deleted",
} as const;
