/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * Oauth 제공자
 */
export type UserProfileDtoProvider =
  (typeof UserProfileDtoProvider)[keyof typeof UserProfileDtoProvider];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserProfileDtoProvider = {
  KAKAO: "kakao",
  GOOGLE: "google",
  NAVER: "naver",
  APPLE: "apple",
} as const;
