/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UserDtoRole } from "./userDtoRole";
import type { UserDtoProvider } from "./userDtoProvider";
import type { UserDtoRefreshToken } from "./userDtoRefreshToken";
import type { UserDtoRefreshTokenExpiresAt } from "./userDtoRefreshTokenExpiresAt";
import type { UserDtoStatus } from "./userDtoStatus";

export interface UserDto {
  /** 회원 고유 ID */
  userId: string;
  /** 회원 이름 */
  name: string;
  /** 회원 역할 */
  role: UserDtoRole;
  /** Oauth 제공자 */
  provider: UserDtoProvider;
  /** Oauth 제공자 ID */
  providerId: string;
  /** refresh token */
  refreshToken: UserDtoRefreshToken;
  /** refresh token 만료 시간 */
  refreshTokenExpiresAt: UserDtoRefreshTokenExpiresAt;
  /** 유저 상태 */
  status: UserDtoStatus;
  /** 마지막 로그인 시간 */
  lastLoginAt: string;
  /** 생성 시간 */
  createdAt: string;
  /** 수정 시간 */
  updatedAt: string;
}
