/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type UserProfileDtoProviderItem =
  (typeof UserProfileDtoProviderItem)[keyof typeof UserProfileDtoProviderItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserProfileDtoProviderItem = {
  kakao: "kakao",
  google: "google",
  naver: "naver",
  apple: "apple",
} as const;
