/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 알림 상태
 */
export type UserNotificationDtoStatus =
  (typeof UserNotificationDtoStatus)[keyof typeof UserNotificationDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserNotificationDtoStatus = {
  read: "read",
  unread: "unread",
  deleted: "deleted",
} as const;
