/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface VerifySlugResponseDto {
  /** 성공 여부 */
  success: boolean;
  /** 메시지 */
  message: string;
  /** 사용 가능 여부 */
  available: boolean;
}
